import type { VenueWithDetails } from '@/types'

// Unsplash photos — free to use, no legal issues
const UNS = 'https://images.unsplash.com/photo-'
const PHOTOS = {
  beachClub:   UNS + '1533174072545-7a4b6ad7a6c3?w=800&h=500&fit=crop&q=80',
  electroClub: UNS + '1571266028243-e4733b0f0bb0?w=800&h=500&fit=crop&q=80',
  luxClub:     UNS + '1566737236500-c8ac43014a67?w=800&h=500&fit=crop&q=80',
  indieClub:   UNS + '1516450360452-9312f5e86fc7?w=800&h=500&fit=crop&q=80',
  technoClub:  UNS + '1574391884720-bbc3740c59d1?w=800&h=500&fit=crop&q=80',
  colorClub:   UNS + '1530103862676-de8c9debad1d?w=800&h=500&fit=crop&q=80',
  rooftop:     UNS + '1492684223066-81342ee5ff30?w=800&h=500&fit=crop&q=80',
  hiphopClub:  UNS + '1516802273409-68526ee1bdd6?w=800&h=500&fit=crop&q=80',
  jazzClub:    UNS + '1415201364774-f6f0bb35f28f?w=800&h=500&fit=crop&q=80',
  cocktailBar: UNS + '1470337458703-46ad1756a187?w=800&h=500&fit=crop&q=80',
  speakeasy:   UNS + '1514362545857-3bc16c4c7d1b?w=800&h=500&fit=crop&q=80',
  vintageBar:  UNS + '1558618666-fcd25c85cd64?w=800&h=500&fit=crop&q=80',
  casualBar:   UNS + '1525268323446-0505b0c3b8b8?w=800&h=500&fit=crop&q=80',
  tapasBar:    UNS + '1559339352-11d035aa65de?w=800&h=500&fit=crop&q=80',
  restaurant:  UNS + '1414235077428-338989a2e8c0?w=800&h=500&fit=crop&q=80',
  luxRestau:   UNS + '1550966871-3ed3cfd9a87e?w=800&h=500&fit=crop&q=80',
  poolParty:   UNS + '1519671482749-fd09be7ccebf?w=800&h=500&fit=crop&q=80',
}

function mkPrice(id: string, venueId: string, label: string, amount: number, amountMax: number | null, includes: string | null, tipus: 'fixed'|'dynamic'|'free_list'|'free', source: 'manual'|'fourvenues'|'scraping' = 'manual', ticketUrl: string | null = null) {
  return { id, venue_id: venueId, label, amount, amount_max: amountMax, currency: 'EUR', includes, entrada_tipus: tipus, ticket_url: ticketUrl, is_current: true, valid_from: '2024-01-01', valid_to: null, last_synced_at: tipus === 'dynamic' ? '2026-06-02T00:00:00Z' : null, source, created_at: '2024-01-01' }
}

function mkRating(id: string, venueId: string, score: number, comment: string) {
  return { id, venue_id: venueId, user_id: null, score, comment, ambients: [], created_at: '2024-01-01' }
}

export const mockVenues: VenueWithDetails[] = [

  // ── CLUBS ────────────────────────────────────────────────────────────────────

  {
    id: '1', name: 'Opium Barcelona', type: 'discoteca',
    description: 'One of Barcelona\'s most famous clubs, right on the beach at the Olympic Port. Combines a Mediterranean restaurant, sea-view terrace and one of the city\'s best dancefloors. Capacity 3,000+. Considered top 10 worldwide.',
    address: 'Passeig Marítim de la Barceloneta, 34', neighborhood: 'Barceloneta',
    lat: 41.3854, lng: 2.1974,
    ambients: ['pijo', 'casual'], music: ['House', 'Electronic', 'Pop'],
    google_rating: 3.9, min_age: 18, dress_code: 'Smart casual',
    image_url: PHOTOS.beachClub, website: 'https://www.opiumbarcelona.com', instagram: '@opiumbarcelona', phone: null,
    opening_hours: { 'Thu–Sun': '23:00–06:00' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('p1a', '1', 'Entry (free with list until 02:00)', 0, null, null, 'free_list'),
      mkPrice('p1b', '1', 'Entry at door', 15, 25, null, 'dynamic', 'fourvenues', 'https://www.opiumbarcelona.com'),
      mkPrice('p1c', '1', 'Spirit / cocktail', 15, 18, null, 'fixed'),
      mkPrice('p1d', '1', 'Shot', 5, 7, null, 'fixed'),
    ],
    ratings: [mkRating('r1a', '1', 4, 'Amazing beach vibe!'), mkRating('r1b', '1', 4, 'Top 10 worldwide for a reason')],
    events: [], avg_rating: 3.9, rating_count: 2,
  },

  {
    id: '2', name: 'Razzmatazz', type: 'discoteca',
    description: 'Barcelona\'s only "hyperclub" with 5 rooms and completely different music styles. Capacity 4,000+. Reference for alternative and electronic music. Hosts international concerts and world-renowned club nights. Top 100 clubs worldwide.',
    address: 'Carrer dels Almogàvers, 122', neighborhood: 'Poblenou',
    lat: 41.4009, lng: 2.1972,
    ambients: ['indie', 'electronica', 'casual'], music: ['Electronic', 'Techno', 'Indie', 'House', 'Pop'],
    google_rating: 4.4, min_age: 18, dress_code: null,
    image_url: PHOTOS.indieClub, website: 'https://www.salarazzmatazz.com', instagram: '@salarazzmatazz', phone: null,
    opening_hours: { 'Wed, Fri–Sat': '01:00–06:00' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('p2a', '2', 'Entry + 1 drink', 13, 20, '1 drink', 'dynamic', 'fourvenues', 'https://www.salarazzmatazz.com'),
      mkPrice('p2b', '2', 'Spirit / cocktail', 12, 15, null, 'fixed'),
      mkPrice('p2c', '2', 'Shot', 4, 6, null, 'fixed'),
    ],
    ratings: [mkRating('r2a', '2', 5, 'Best indie/electronic club in Europe'), mkRating('r2b', '2', 4, '5 rooms, endless night')],
    events: [
      { id: 'e2', venue_id: '2', name: 'Nitsa Electronic Night', date: '2026-06-07', doors_open: '01:00', price_min: 13, price_max: 18, currency: 'EUR', ticket_url: 'https://www.salarazzmatazz.com', artists: ['Bicep', 'Four Tet'], genre: 'Electronic', source_id: null, source: 'manual', created_at: '2024-01-01' },
    ],
    avg_rating: 4.4, rating_count: 2,
  },

  {
    id: '3', name: 'Sutton Club', type: 'discoteca',
    description: 'Iconic club in the upper part of Barcelona, favourite of the locals. Exclusive and elegant crowd, strict door policy. Top 20 clubs worldwide. The go-to spot for Barcelona\'s in-crowd.',
    address: 'Carrer de Tuset, 13', neighborhood: 'Zona Alta',
    lat: 41.3974, lng: 2.1504,
    ambients: ['pijo'], music: ['Pop', 'R&B', 'Hip-Hop', 'Reggaeton'],
    google_rating: 3.8, min_age: 18, dress_code: 'Elegant — strictly enforced',
    image_url: PHOTOS.luxClub, website: 'https://www.thesuttonclub.com', instagram: '@suttonbcn', phone: null,
    opening_hours: { 'Thu–Sat': '23:30–06:00' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('p3a', '3', 'Entry + 1 drink', 20, 30, '1 drink', 'dynamic', 'fourvenues', 'https://www.thesuttonclub.com'),
      mkPrice('p3b', '3', 'Spirit / cocktail', 15, 20, null, 'fixed'),
      mkPrice('p3c', '3', 'Shot', 6, 8, null, 'fixed'),
      mkPrice('p3d', '3', 'VIP table minimum', 300, null, 'bottle service', 'fixed'),
    ],
    ratings: [mkRating('r3a', '3', 4, 'The pijo club par excellence'), mkRating('r3b', '3', 4, 'Strict door but worth it')],
    events: [], avg_rating: 3.8, rating_count: 2,
  },

  {
    id: '4', name: 'Pacha Barcelona', type: 'discoteca',
    description: 'The Ibiza legend lands in Barcelona, right on the seafront. Glamorous atmosphere, international DJs and renowned themed parties. Includes restaurant and lounge area. Famous for "El Paripé" afternoon parties and exclusive events.',
    address: 'Passeig Marítim de la Barceloneta, 38', neighborhood: 'Barceloneta',
    lat: 41.3856, lng: 2.1978,
    ambients: ['pijo', 'casual'], music: ['House', 'Electronic', 'Pop'],
    google_rating: 3.8, min_age: 18, dress_code: 'Smart casual',
    image_url: PHOTOS.beachClub, website: null, instagram: '@pachabarcelona', phone: null,
    opening_hours: { 'Thu–Sun': '23:00–06:00' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('p4a', '4', 'Entry + 1 drink', 20, 25, '1 drink', 'dynamic', 'fourvenues', 'https://www.pacha-barcelona.com'),
      mkPrice('p4b', '4', 'Spirit / cocktail', 15, 18, null, 'fixed'),
      mkPrice('p4c', '4', 'Shot', 5, 7, null, 'fixed'),
    ],
    ratings: [mkRating('r4a', '4', 4, 'El Paripé afternoon parties are unmissable'), mkRating('r4b', '4', 4, 'Classic Ibiza vibes in BCN')],
    events: [], avg_rating: 3.8, rating_count: 2,
  },

  {
    id: '5', name: 'Shôko Club', type: 'discoteca',
    description: 'Beach club with Asian fusion restaurant and nightclub. Located right next to Opium — together they form the heart of the Olympic Port nightlife. Spectacular terrace with sea views. Top 5 clubs worldwide at its peak.',
    address: 'Passeig Marítim de la Barceloneta, 36', neighborhood: 'Barceloneta',
    lat: 41.3855, lng: 2.1976,
    ambients: ['pijo', 'casual'], music: ['House', 'Electronic', 'Pop', 'R&B'],
    google_rating: 3.9, min_age: 18, dress_code: 'Smart casual',
    image_url: PHOTOS.beachClub, website: null, instagram: '@shokobarcelona', phone: null,
    opening_hours: { 'Wed–Sun': '23:00–06:00' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('p5a', '5', 'Free entry with list (until 01:30)', 0, null, null, 'free_list'),
      mkPrice('p5b', '5', 'Entry at door', 15, 25, null, 'dynamic', 'fourvenues', 'https://www.shoko.biz/barcelona'),
      mkPrice('p5c', '5', 'Spirit / cocktail', 14, 18, null, 'fixed'),
    ],
    ratings: [mkRating('r5a', '5', 4, 'Best terrace on the seafront'), mkRating('r5b', '5', 4, 'Great Asian food before the club')],
    events: [], avg_rating: 3.9, rating_count: 2,
  },

  {
    id: '6', name: 'Otto Zutz', type: 'discoteca',
    description: 'Hip-Hop and Reggaeton temple with 3 floors of different music. Mixed crowd of local uni students and international tourists. 4-floor modernist building converted into a club. Accessible guest-list policy.',
    address: 'Carrer de Lincoln, 15', neighborhood: 'Zona Alta',
    lat: 41.4005, lng: 2.1430,
    ambients: ['casual', 'indie'], music: ['Hip-Hop', 'Reggaeton', 'R&B', 'Pop'],
    google_rating: 3.7, min_age: 18, dress_code: 'Smart casual',
    image_url: PHOTOS.hiphopClub, website: null, instagram: '@ottuzutz_bcn', phone: null,
    opening_hours: { 'Wed–Sat': 'from 23:30' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('p6a', '6', 'Free entry (guest list)', 0, null, null, 'free_list'),
      mkPrice('p6b', '6', 'Entry at door', 10, 20, null, 'dynamic', 'fourvenues', 'https://www.ottozutz.com'),
      mkPrice('p6c', '6', 'Spirit / cocktail', 12, 15, null, 'fixed'),
    ],
    ratings: [mkRating('r6a', '6', 4, '3 floors, always something good'), mkRating('r6b', '6', 3, 'Gets very crowded on Saturdays')],
    events: [], avg_rating: 3.7, rating_count: 2,
  },

  {
    id: '7', name: 'Sala Apolo', type: 'discoteca',
    description: 'Historic 1940s venue converted into a reference for alternative music. Live concerts and club nights. La Nitsa is Barcelona\'s flagship electronic session. Iconic space with vintage decor. Prices vary by event — auto-synced.',
    address: 'Carrer Nou de la Rambla, 113', neighborhood: 'Paral·lel',
    lat: 41.3745, lng: 2.1647,
    ambients: ['indie', 'casual'], music: ['Indie', 'Electronic', 'Techno', 'House'],
    google_rating: 4.4, min_age: 18, dress_code: null,
    image_url: PHOTOS.colorClub, website: 'https://www.sala-apolo.com', instagram: '@salaapolo', phone: null,
    opening_hours: { 'Fri–Sat': '23:55–06:00' },
    price_sync_url: 'https://www.sala-apolo.com/agenda', price_sync_source: 'scraping', created_at: '2024-01-01',
    prices: [
      mkPrice('p7a', '7', 'Entry (varies by event)', 12, 20, null, 'dynamic', 'scraping', 'https://www.sala-apolo.com'),
      mkPrice('p7b', '7', 'Spirit / cocktail', 10, 14, null, 'fixed'),
      mkPrice('p7c', '7', 'Shot', 4, 5, null, 'fixed'),
    ],
    ratings: [mkRating('r7a', '7', 5, 'La Nitsa is one of the best in Europe'), mkRating('r7b', '7', 4, 'Iconic historic venue')],
    events: [], avg_rating: 4.4, rating_count: 2,
  },

  {
    id: '8', name: 'Bling Bling Barcelona', type: 'discoteca',
    description: 'The most exclusive and glamorous club in Barcelona, the reference for the local high society. Luxurious design, very selective door policy and VIP atmosphere par excellence. Top 15 clubs worldwide. Direct neighbour of Sutton on Carrer Tuset.',
    address: 'Carrer de Tuset, 10', neighborhood: 'Zona Alta',
    lat: 41.3971, lng: 2.1498,
    ambients: ['pijo'], music: ['Pop', 'R&B', 'Reggaeton', 'Hip-Hop'],
    google_rating: 3.6, min_age: 18, dress_code: 'Elegant — very selective',
    image_url: PHOTOS.luxClub, website: null, instagram: '@blingblingbcn', phone: null,
    opening_hours: { 'Thu–Sat': 'from 23:30' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('p8a', '8', 'Entry + 1 drink', 25, 40, '1 drink', 'dynamic', 'fourvenues', 'https://www.blingblingbarcelona.com'),
      mkPrice('p8b', '8', 'Spirit / cocktail', 18, 25, null, 'fixed'),
      mkPrice('p8c', '8', 'Shot', 7, 10, null, 'fixed'),
    ],
    ratings: [mkRating('r8a', '8', 4, 'Most glamorous club in BCN'), mkRating('r8b', '8', 3, 'Very selective door')],
    events: [], avg_rating: 3.6, rating_count: 2,
  },

  {
    id: '9', name: 'La Fira', type: 'discoteca',
    description: 'Themed club set in a 1920s fairground. Unique decor with fairground mirrors, carousel horses and neon lights. Very popular with uni students. Relaxed and accessible atmosphere. Two rooms with different music.',
    address: 'Carrer de Villarroel, 207', neighborhood: 'Eixample',
    lat: 41.3920, lng: 2.1545,
    ambients: ['casual', 'indie'], music: ['Reggaeton', 'Pop', 'Hip-Hop'],
    google_rating: 4.0, min_age: 18, dress_code: null,
    image_url: PHOTOS.colorClub, website: null, instagram: '@lafiravillarroel', phone: null,
    opening_hours: { 'Thu–Sat': 'from 23:00' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('p9a', '9', 'Entry + 1 drink', 10, 15, '1 drink', 'dynamic', 'fourvenues', 'https://lafirabarcelona.com'),
      mkPrice('p9b', '9', 'Spirit / cocktail', 10, 13, null, 'fixed'),
      mkPrice('p9c', '9', 'Shot', 3, 5, null, 'fixed'),
    ],
    ratings: [mkRating('r9a', '9', 4, 'Most unique decor in Barcelona'), mkRating('r9b', '9', 4, 'Great student night vibes')],
    events: [], avg_rating: 4.0, rating_count: 2,
  },

  {
    id: '10', name: 'Noxe (Hotel W)', type: 'discoteca',
    description: 'Club on floor 26 of the iconic Hotel W Barcelona, with 360° panoramic views over the city and the Mediterranean. Glamorous and exclusive atmosphere. Ideal for hotel guests and luxury crowd.',
    address: 'Plaça de la Rosa dels Vents, 1 (Floor 26, Hotel W)', neighborhood: 'Barceloneta',
    lat: 41.3720, lng: 2.1782,
    ambients: ['pijo'], music: ['House', 'Electronic'],
    google_rating: 4.0, min_age: 18, dress_code: 'Elegant',
    image_url: PHOTOS.rooftop, website: null, instagram: '@noxebarcelona', phone: null,
    opening_hours: { 'Fri–Sat': 'from 23:00' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('p10a', '10', 'Entry', 20, 30, null, 'dynamic', 'fourvenues', 'https://www.w-barcelona.com'),
      mkPrice('p10b', '10', 'Spirit / cocktail', 18, 22, null, 'fixed'),
      mkPrice('p10c', '10', 'Shot', 7, 9, null, 'fixed'),
    ],
    ratings: [mkRating('r10a', '10', 5, '360° views are absolutely stunning'), mkRating('r10b', '10', 4, 'Most exclusive views in BCN')],
    events: [], avg_rating: 4.0, rating_count: 2,
  },

  {
    id: '11', name: 'CDLC', type: 'discoteca',
    description: 'Reference club-restaurant at the Vila Olímpica. Combines Asian fusion restaurant, lounge terrace with sofas and nightclub. Open every day. Exclusive national and international crowd. VIP area with curtains for privacy. Top 100 clubs worldwide.',
    address: 'Passeig Marítim de la Barceloneta, 32', neighborhood: 'Barceloneta',
    lat: 41.3853, lng: 2.1972,
    ambients: ['pijo', 'casual'], music: ['Deep House', 'Tech House', 'Electronic'],
    google_rating: 3.9, min_age: 18, dress_code: 'Smart casual',
    image_url: PHOTOS.beachClub, website: null, instagram: '@cdlcbarcelona', phone: null,
    opening_hours: { 'Daily': '23:00–06:00' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('p11a', '11', 'Free entry (guest list)', 0, null, null, 'free_list'),
      mkPrice('p11b', '11', 'Entry at door', 15, 25, null, 'dynamic', 'fourvenues', 'https://www.cdlcbarcelona.com'),
      mkPrice('p11c', '11', 'Spirit / cocktail', 14, 18, null, 'fixed'),
    ],
    ratings: [mkRating('r11a', '11', 4, 'Great vibe every night of the week'), mkRating('r11b', '11', 4, 'VIP lounge is gorgeous')],
    events: [], avg_rating: 3.9, rating_count: 2,
  },

  {
    id: '12', name: 'Jamboree', type: 'discoteca',
    description: 'Jazz club and nightclub in the basement of Plaça Reial. Since 1960, a reference for live jazz and hip-hop. Monday jazz concerts (WTF Jazz Club). Intimate and underground atmosphere, very authentic.',
    address: 'Plaça Reial, 17', neighborhood: 'Barri Gòtic',
    lat: 41.3797, lng: 2.1750,
    ambients: ['casual', 'soul'], music: ['Jazz', 'Hip-Hop', 'R&B', 'Soul'],
    google_rating: 4.2, min_age: 18, dress_code: null,
    image_url: PHOTOS.jazzClub, website: null, instagram: '@jamboreejazzclub', phone: null,
    opening_hours: { 'Daily': 'from 20:00' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('p12a', '12', 'Entry (varies by event)', 10, 15, null, 'dynamic', 'fourvenues', 'https://www.masimas.com/jamboree'),
      mkPrice('p12b', '12', 'Spirit / cocktail', 10, 13, null, 'fixed'),
      mkPrice('p12c', '12', 'Shot', 4, 5, null, 'fixed'),
    ],
    ratings: [mkRating('r12a', '12', 5, 'Monday jazz night is a BCN institution'), mkRating('r12b', '12', 4, 'Most authentic club in the Gothic Quarter')],
    events: [], avg_rating: 4.2, rating_count: 2,
  },

  {
    id: '26', name: 'Sea Sea Club', type: 'discoteca',
    description: 'Open-air summer club with pool, terrace and 4 rooms. The go-to destination for festival pool parties in summer. Restaurant option. Huge capacity. International DJs. Very popular during Sónar festival season.',
    address: 'Rambla Prim, 17 (Port Fòrum)', neighborhood: 'Fòrum',
    lat: 41.4100, lng: 2.2250,
    ambients: ['casual', 'pijo'], music: ['Electronic', 'House', 'Pop'],
    google_rating: 4.0, min_age: 18, dress_code: null,
    image_url: PHOTOS.poolParty, website: null, instagram: '@seaseaclub', phone: null,
    opening_hours: { 'Fri–Sun': 'from 22:00' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('p26a', '26', 'Entry (varies by event)', 20, 35, null, 'dynamic', 'fourvenues', 'https://www.seaseaclub.com'),
      mkPrice('p26b', '26', 'Spirit / cocktail', 14, 18, null, 'fixed'),
    ],
    ratings: [mkRating('r26a', '26', 4, 'Best pool parties in summer'), mkRating('r26b', '26', 4, 'Unmissable during Sónar')],
    events: [], avg_rating: 4.0, rating_count: 2,
  },

  {
    id: '4_in', name: 'Input Dance Club', type: 'discoteca',
    description: 'Temple of underground techno and electronic music. Best sound system in Barcelona.',
    address: 'Carrer de Gran Via de les Corts Catalanes, 235', neighborhood: 'Sants',
    lat: 41.3748, lng: 2.1378,
    ambients: ['techno', 'electronica'], music: ['Techno', 'Electronic'],
    google_rating: null, min_age: 18, dress_code: null,
    image_url: PHOTOS.technoClub, website: 'https://www.inputbcn.com', instagram: '@inputbcn', phone: null,
    opening_hours: { 'Sat–Sun': '00:00–12:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [mkPrice('p_in', '4_in', 'Entry', 18, null, null, 'fixed')],
    ratings: [mkRating('r_in1', '4_in', 5, 'Best sound system in BCN')],
    events: [], avg_rating: 5, rating_count: 1,
  },

  {
    id: '5_mac', name: 'Macarena Club', type: 'discoteca',
    description: 'Hidden gem in the Gothic Quarter. Reggaeton and Latin music all night long. Free entry.',
    address: 'Carrer Nou de Sant Francesc, 5', neighborhood: 'Barri Gòtic',
    lat: 41.3797, lng: 2.1766,
    ambients: ['reggaeton', 'latin'], music: ['Reggaeton', 'Latin'],
    google_rating: null, min_age: 18, dress_code: null,
    image_url: PHOTOS.electroClub, website: null, instagram: '@macarenaclub', phone: null,
    opening_hours: { 'Daily': '00:00–05:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [mkPrice('p_mac', '5_mac', 'Free entry', 0, null, null, 'free')],
    ratings: [mkRating('r_mac', '5_mac', 4, 'Very intimate and great Latin vibes')],
    events: [], avg_rating: 4, rating_count: 1,
  },

  // ── COCKTAIL BARS ────────────────────────────────────────────────────────────

  {
    id: '13', name: 'Sips', type: 'bar',
    description: 'Voted #1 in the World\'s 50 Best Bars. Founded by Simone Caporale and Marc Álvarez. Minimalist and innovative approach, signature cocktails. Reservation practically required. Inside there\'s a secret bar "Esencia" with a liquid tasting menu.',
    address: 'Carrer de Muntaner, 108', neighborhood: 'Eixample',
    lat: 41.3870, lng: 2.1545,
    ambients: ['pijo', 'casual'], music: ['House', 'Jazz'],
    google_rating: 4.6, min_age: 18, dress_code: 'Smart casual',
    image_url: PHOTOS.cocktailBar, website: null, instagram: '@sips_bcn', phone: null,
    opening_hours: { 'Tue–Sat': '17:00–01:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('p13a', '13', 'Entry', 0, null, null, 'free'),
      mkPrice('p13b', '13', 'Signature cocktail', 16, 20, null, 'fixed'),
    ],
    ratings: [mkRating('r13a', '13', 5, '#1 bar in the world — worth every cent'), mkRating('r13b', '13', 5, 'Book weeks in advance')],
    events: [], avg_rating: 4.6, rating_count: 2,
  },

  {
    id: '14', name: 'Paradiso', type: 'bar',
    description: 'Speakeasy hidden behind a fridge in a pastrami deli. One of the world\'s best cocktail bars. Stunning modernist interior that feels like another world. Reservation strongly recommended. World\'s 50 Best Bars award winner.',
    address: 'Carrer de Rera Palau, 4', neighborhood: 'El Born',
    lat: 41.3845, lng: 2.1819,
    ambients: ['casual', 'indie'], music: ['Jazz', 'Soul', 'Electronic'],
    google_rating: 4.6, min_age: 18, dress_code: null,
    image_url: PHOTOS.speakeasy, website: null, instagram: '@paradiso_bcn', phone: null,
    opening_hours: { 'Tue–Sun': '17:00–01:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('p14a', '14', 'Entry', 0, null, null, 'free'),
      mkPrice('p14b', '14', 'Signature cocktail', 16, 20, null, 'fixed'),
    ],
    ratings: [mkRating('r14a', '14', 5, 'Hidden gem, find the fridge door!'), mkRating('r14b', '14', 5, 'World class cocktails')],
    events: [], avg_rating: 4.6, rating_count: 2,
  },

  {
    id: '15', name: 'Dr. Stravinsky', type: 'bar',
    description: 'Signature cocktail bar with an interior evoking an alchemist\'s laboratory. Shelves full of flasks and bottles. Innovative and surprising cocktail menu. One of El Born\'s best-kept secrets. Intimate bohemian atmosphere.',
    address: 'Carrer dels Mirallers, 5', neighborhood: 'El Born',
    lat: 41.3843, lng: 2.1816,
    ambients: ['indie', 'casual'], music: ['Jazz', 'Electronic'],
    google_rating: 4.5, min_age: 18, dress_code: null,
    image_url: PHOTOS.speakeasy, website: null, instagram: '@drstravinsky_bcn', phone: null,
    opening_hours: { 'Tue–Sun': '18:00–02:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('p15a', '15', 'Entry', 0, null, null, 'free'),
      mkPrice('p15b', '15', 'Signature cocktail', 13, 16, null, 'fixed'),
    ],
    ratings: [mkRating('r15a', '15', 5, 'Feels like drinking in a wizard\'s lab'), mkRating('r15b', '15', 4, 'Underrated gem of El Born')],
    events: [], avg_rating: 4.5, rating_count: 2,
  },

  {
    id: '16', name: 'Dry Martini', type: 'bar',
    description: 'A Barcelona cocktail legend since 1978. Temple of the classic Martini, with the recipe on the wall. Elegant and timeless atmosphere. Run by Javier de las Muelas, a world reference in mixology. Featured in countless international guides.',
    address: 'Carrer d\'Aribau, 162', neighborhood: 'Eixample',
    lat: 41.3912, lng: 2.1548,
    ambients: ['pijo'], music: ['Jazz', 'Soul'],
    google_rating: 4.5, min_age: 18, dress_code: 'Smart',
    image_url: PHOTOS.cocktailBar, website: null, instagram: '@drymartinibarcelona', phone: null,
    opening_hours: { 'Mon–Sat': '13:00–02:30' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('p16a', '16', 'Entry', 0, null, null, 'free'),
      mkPrice('p16b', '16', 'Classic cocktail', 15, 18, null, 'fixed'),
    ],
    ratings: [mkRating('r16a', '16', 5, 'The best Martini in the world, no contest'), mkRating('r16b', '16', 5, 'A Barcelona institution since 1978')],
    events: [], avg_rating: 4.5, rating_count: 2,
  },

  {
    id: 'marsella', name: 'Bar Marsella', type: 'bar',
    description: 'The oldest bar in Barcelona (1820). Absinthe and classic cocktails in a unique atmosphere. A must-visit.',
    address: 'Carrer dels Escudellers Blancs, 3', neighborhood: 'Barri Gòtic',
    lat: 41.3797, lng: 2.1748,
    ambients: ['indie', 'casual'], music: ['Soul', 'Jazz'],
    google_rating: null, min_age: 18, dress_code: null,
    image_url: PHOTOS.vintageBar, website: null, instagram: null, phone: null,
    opening_hours: { 'Mon–Sat': '22:00–02:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [mkPrice('p_mar', 'marsella', 'Average drink', 8, null, null, 'fixed')],
    ratings: [mkRating('r_mar', 'marsella', 5, 'Oldest bar in Barcelona — timeless')],
    events: [], avg_rating: 5, rating_count: 1,
  },

  // ── PRE-PARTY BARS ───────────────────────────────────────────────────────────

  {
    id: '17', name: 'Espit Chupitos', type: 'previa',
    description: 'Specialist shot bar with hundreds of themed and surprising options. The go-to place to kick off the night. Budget prices (~€2/shot). Great for groups. Two strategic locations: Eixample (near Sutton/Otto Zutz) and Gothic (near Plaça Reial).',
    address: 'Carrer d\'Aribau, 77 / Passatge de Colom, 8', neighborhood: 'Eixample',
    lat: 41.3882, lng: 2.1560,
    ambients: ['casual'], music: ['Pop', 'Reggaeton'],
    google_rating: 4.3, min_age: 18, dress_code: null,
    image_url: PHOTOS.casualBar, website: null, instagram: '@espitchupitos', phone: null,
    opening_hours: { 'Daily': '20:00–03:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('p17a', '17', 'Entry', 0, null, null, 'free'),
      mkPrice('p17b', '17', 'Shot', 2, 3, null, 'fixed'),
      mkPrice('p17c', '17', 'Spirit + mixer', 5, 8, null, 'fixed'),
    ],
    ratings: [mkRating('r17a', '17', 4, 'Best value pre-party spot in BCN'), mkRating('r17b', '17', 5, 'Hundreds of shot options!')],
    events: [], avg_rating: 4.3, rating_count: 2,
  },

  {
    id: '18', name: 'Milk Bar', type: 'previa',
    description: 'Classic cocktail bar in the Gothic Quarter with retro decor and lively atmosphere. Open all day, ideal to start the night. Quality cocktails at great prices. Close to the clubs of Plaça Reial (Jamboree, Sidecar, Karma).',
    address: 'Carrer d\'en Gignàs, 21', neighborhood: 'Barri Gòtic',
    lat: 41.3807, lng: 2.1768,
    ambients: ['casual', 'indie'], music: ['Indie', 'Pop', 'Soul'],
    google_rating: 4.3, min_age: 18, dress_code: null,
    image_url: PHOTOS.vintageBar, website: null, instagram: '@milkbarbarcelona', phone: null,
    opening_hours: { 'Daily': '10:00–03:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('p18a', '18', 'Entry', 0, null, null, 'free'),
      mkPrice('p18b', '18', 'Cocktail', 8, 12, null, 'fixed'),
      mkPrice('p18c', '18', 'Shot', 3, 5, null, 'fixed'),
    ],
    ratings: [mkRating('r18a', '18', 4, 'Perfect start to the night in the Gothic'), mkRating('r18b', '18', 4, 'Great cocktails for the price')],
    events: [], avg_rating: 4.3, rating_count: 2,
  },

  {
    id: '19', name: 'Marmalade', type: 'previa',
    description: 'Restaurant-cocktail bar with an elegant-vintage interior inspired by "1950s Havana meets New York". High ceilings, ambient lighting and glamorous kitsch furniture. Extensive cocktail menu. Open all day. Close to Sala Apolo.',
    address: 'Carrer Riera Alta, 4–6', neighborhood: 'El Raval',
    lat: 41.3815, lng: 2.1678,
    ambients: ['casual', 'indie'], music: ['Soul', 'R&B', 'Indie'],
    google_rating: 4.2, min_age: 18, dress_code: null,
    image_url: PHOTOS.casualBar, website: null, instagram: '@marmaladebarcelona', phone: null,
    opening_hours: { 'Daily': '10:00–03:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('p19a', '19', 'Entry', 0, null, null, 'free'),
      mkPrice('p19b', '19', 'Cocktail', 9, 13, null, 'fixed'),
      mkPrice('p19c', '19', 'Shot', 3, 5, null, 'fixed'),
    ],
    ratings: [mkRating('r19a', '19', 4, 'Beautiful decor, great cocktails'), mkRating('r19b', '19', 4, 'Havana vibes in Barcelona')],
    events: [], avg_rating: 4.2, rating_count: 2,
  },

  {
    id: '20', name: 'El Xampanyet', type: 'previa',
    description: 'Iconic tapas and cava bar in El Born since the 1940s. The perfect spot for an aperitivo or pre-party with authentic tapas. Very popular house cava. Genuinely Barcelonian atmosphere.',
    address: 'Carrer de Montcada, 22', neighborhood: 'El Born',
    lat: 41.3843, lng: 2.1811,
    ambients: ['casual'], music: ['Jazz', 'Soul'],
    google_rating: 4.4, min_age: 0, dress_code: null,
    image_url: PHOTOS.tapasBar, website: null, instagram: '@elxampanyet_born', phone: null,
    opening_hours: { 'Tue–Sat': '19:00–23:30' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('p20a', '20', 'Entry', 0, null, null, 'free'),
      mkPrice('p20b', '20', 'House cava (glass)', 3, 4, null, 'fixed'),
      mkPrice('p20c', '20', 'Tapa', 2, 4, null, 'fixed'),
      mkPrice('p20d', '20', 'Cocktail', 4, 6, null, 'fixed'),
    ],
    ratings: [mkRating('r20a', '20', 5, 'Most authentic pre-party in BCN'), mkRating('r20b', '20', 4, 'The house cava is incredible')],
    events: [], avg_rating: 4.4, rating_count: 2,
  },

  {
    id: '21', name: 'Bar Calders', type: 'previa',
    description: 'Iconic bar in Sant Antoni, epicentre of Barcelona\'s most hipster neighbourhood. Very popular terrace, vibrant neighbourhood atmosphere. The meeting point of Carrer Parlament, with the best terraces in the area. Perfect for a relaxed social pre-party.',
    address: 'Carrer del Parlament, 25', neighborhood: 'Sant Antoni',
    lat: 41.3820, lng: 2.1601,
    ambients: ['casual', 'indie'], music: ['Indie', 'Pop'],
    google_rating: 4.4, min_age: 18, dress_code: null,
    image_url: PHOTOS.casualBar, website: null, instagram: '@barcalders', phone: null,
    opening_hours: { 'Daily': '09:00–02:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('p21a', '21', 'Entry', 0, null, null, 'free'),
      mkPrice('p21b', '21', 'Cocktail', 7, 10, null, 'fixed'),
      mkPrice('p21c', '21', 'Shot', 3, 4, null, 'fixed'),
    ],
    ratings: [mkRating('r21a', '21', 4, 'Best terrace in Sant Antoni'), mkRating('r21b', '21', 5, 'Hipster neighbourhood at its finest')],
    events: [], avg_rating: 4.4, rating_count: 2,
  },

  {
    id: 'laprevia', name: 'La Previa', type: 'previa',
    description: 'Lively pre-party bar in Poblenou with live DJs playing current hits. Young, mixed crowd — perfect before heading to Razzmatazz or Wolf.',
    address: 'Carrer de Pallars, Barcelona', neighborhood: 'Poblenou',
    lat: 41.4013, lng: 2.1950,
    ambients: ['pop', 'reggaeton', 'casual'], music: ['Pop', 'Reggaeton'],
    google_rating: null, min_age: 18, dress_code: null,
    image_url: PHOTOS.casualBar, website: null, instagram: null, phone: null,
    opening_hours: { 'Daily': '23:00–03:30' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('p_lp_a', 'laprevia', 'Entry', 0, null, null, 'free'),
      mkPrice('p_lp_b', 'laprevia', 'Spirit + mixer', 7, null, null, 'fixed'),
      mkPrice('p_lp_c', 'laprevia', 'Beer', 4, null, null, 'fixed'),
    ],
    ratings: [mkRating('r_lp', 'laprevia', 5, 'Best pre-party in Poblenou')],
    events: [], avg_rating: 4.7, rating_count: 1,
  },

  {
    id: 'ovellam', name: "L'Ovella Negra (Marina)", type: 'previa',
    description: 'University-favourite tavern right next to Razzmatazz — the perfect pre-party for big groups. Relaxed vibe, cheap pitchers and sangria.',
    address: 'Carrer dels Almogàvers, Poblenou', neighborhood: 'Poblenou',
    lat: 41.4007, lng: 2.1960,
    ambients: ['casual', 'indie'], music: ['Indie', 'Pop'],
    google_rating: null, min_age: 18, dress_code: null,
    image_url: PHOTOS.casualBar, website: null, instagram: null, phone: null,
    opening_hours: { 'Daily': 'until 03:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('p_om_a', 'ovellam', 'Entry', 0, null, null, 'free'),
      mkPrice('p_om_b', 'ovellam', 'Beer pitcher', 6, null, null, 'fixed'),
      mkPrice('p_om_c', 'ovellam', 'Sangria', 5, null, null, 'fixed'),
    ],
    ratings: [mkRating('r_om', 'ovellam', 4, 'Cheapest pre-party near Razzmatazz')],
    events: [], avg_rating: 4.2, rating_count: 1,
  },

  // ── RESTAURANTS ──────────────────────────────────────────────────────────────

  {
    id: '22', name: 'CDLC Restaurant', type: 'restaurant',
    description: 'Lounge restaurant serving Asian fusion cuisine on the seafront. DJ sessions during dinner. Terrace with sofas and Mediterranean views. Open every day. Perfect for dinner that naturally flows into the adjacent club. Exclusive atmosphere.',
    address: 'Passeig Marítim de la Barceloneta, 32', neighborhood: 'Barceloneta',
    lat: 41.3853, lng: 2.1972,
    ambients: ['pijo', 'casual'], music: ['Deep House', 'Electronic', 'World Music'],
    google_rating: 3.9, min_age: 0, dress_code: null,
    image_url: PHOTOS.restaurant, website: null, instagram: '@cdlcbarcelona', phone: null,
    opening_hours: { 'Daily': '13:00–01:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('p22a', '22', 'Entry (restaurant)', 0, null, null, 'free'),
      mkPrice('p22b', '22', 'Dinner per person', 35, 60, 'food only', 'fixed'),
      mkPrice('p22c', '22', 'Cocktail', 14, 18, null, 'fixed'),
    ],
    ratings: [mkRating('r22a', '22', 4, 'Dinner + club in one place'), mkRating('r22b', '22', 4, 'Sea views are outstanding')],
    events: [], avg_rating: 3.9, rating_count: 2,
  },

  {
    id: '23', name: 'Cachitos', type: 'restaurant',
    description: 'Tapas and Mediterranean-Spanish restaurant with a festive atmosphere and music sessions. Sharing concept. Quality rice dishes, tapas and montaditos. Two strategic locations. Ideal for group dinner before a night out.',
    address: 'Rambla de Catalunya, 30', neighborhood: 'Eixample',
    lat: 41.3917, lng: 2.1600,
    ambients: ['casual', 'pijo'], music: ['Pop', 'Latin', 'Soul'],
    google_rating: 4.3, min_age: 0, dress_code: null,
    image_url: PHOTOS.restaurant, website: null, instagram: '@cachitosbarcelona', phone: null,
    opening_hours: { 'Daily': '13:00–00:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('p23a', '23', 'Dinner per person', 25, 40, 'food only', 'fixed'),
      mkPrice('p23b', '23', 'Cocktail', 10, 14, null, 'fixed'),
    ],
    ratings: [mkRating('r23a', '23', 4, 'Best tapas for group dinner'), mkRating('r23b', '23', 4, 'Great atmosphere, feels like a party')],
    events: [], avg_rating: 4.3, rating_count: 2,
  },

  {
    id: '24', name: 'Gatsby Barcelona', type: 'restaurant',
    description: 'High-end restaurant inspired by the Jazz Age of the 1920s, on the same Carrer Tuset as Sutton and Bling Bling. Ideal for a luxurious dinner before the clubs next door. Elegant and festive, live DJ sessions.',
    address: 'Carrer de Tuset, 19', neighborhood: 'Zona Alta',
    lat: 41.3976, lng: 2.1505,
    ambients: ['pijo'], music: ['Jazz', 'Soul', 'Pop'],
    google_rating: 4.2, min_age: 0, dress_code: 'Smart',
    image_url: PHOTOS.luxRestau, website: null, instagram: '@gatsby_bcn', phone: null,
    opening_hours: { 'Tue–Sat': '20:00–01:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('p24a', '24', 'Dinner per person', 45, 80, 'food only', 'fixed'),
      mkPrice('p24b', '24', 'Cocktail', 14, 18, null, 'fixed'),
    ],
    ratings: [mkRating('r24a', '24', 4, 'Perfect start before Sutton or Bling Bling'), mkRating('r24b', '24', 5, 'Stunning Jazz Age decor')],
    events: [], avg_rating: 4.2, rating_count: 2,
  },

  {
    id: '25', name: 'Shôko Restaurant', type: 'restaurant',
    description: 'Japanese-Peruvian fusion (Nikkei) restaurant on the seafront. Terrace opens with a DJ at sunset and transforms into a club at night. Perfect for dinner and staying for the party in the same venue. Mediterranean views.',
    address: 'Passeig Marítim de la Barceloneta, 36', neighborhood: 'Barceloneta',
    lat: 41.3855, lng: 2.1976,
    ambients: ['pijo', 'casual'], music: ['House', 'Electronic', 'Pop'],
    google_rating: 3.9, min_age: 0, dress_code: null,
    image_url: PHOTOS.restaurant, website: null, instagram: '@shokobarcelona', phone: null,
    opening_hours: { 'Wed–Sun': '13:00–01:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('p25a', '25', 'Dinner per person', 35, 55, 'food only', 'fixed'),
      mkPrice('p25b', '25', 'Cocktail', 13, 17, null, 'fixed'),
    ],
    ratings: [mkRating('r25a', '25', 4, 'Dinner to club in the same spot'), mkRating('r25b', '25', 4, 'Nikkei cuisine is outstanding')],
    events: [], avg_rating: 3.9, rating_count: 2,
  },

  {
    id: 'pepita', name: 'La Pepita BCN', type: 'restaurant',
    description: 'Typical Barcelona patatas bravas and croquettes. Casual and quality dinner spot.',
    address: 'Carrer de Còrsega, 343', neighborhood: 'Eixample',
    lat: 41.3984, lng: 2.1631,
    ambients: ['casual', 'indie'], music: ['Indie', 'Pop'],
    google_rating: null, min_age: 0, dress_code: null,
    image_url: PHOTOS.tapasBar, website: null, instagram: null, phone: null,
    opening_hours: { 'Daily': '13:00–23:30' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [mkPrice('p_pep', 'pepita', 'Dinner per person', 20, null, 'food and drinks', 'fixed')],
    ratings: [], events: [], avg_rating: 0, rating_count: 0,
  },

  // ── NEW PRE-PARTY BARS ───────────────────────────────────────────────────────

  {
    id: 'bbplus', name: 'BB+', type: 'previa',
    description: 'Popular pre-party cocktail bar in Eixample. Affordable drinks, relaxed vibe and a young crowd. Great spot before heading to Sutton or Otto Zutz. Known for strong cocktails at budget-friendly prices.',
    address: 'Carrer del Rosselló, 164', neighborhood: 'Eixample',
    lat: 41.3938, lng: 2.1558,
    ambients: ['casual', 'indie'], music: ['Pop', 'Indie', 'Reggaeton'],
    google_rating: 4.1, min_age: 18, dress_code: null,
    image_url: PHOTOS.casualBar, website: null, instagram: '@bbplus_bcn', phone: '+34 616 41 95 49',
    opening_hours: { 'Daily': '20:00–03:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('pbb1', 'bbplus', 'Entry', 0, null, null, 'free'),
      mkPrice('pbb2', 'bbplus', 'Cocktail', 7, 10, null, 'fixed'),
      mkPrice('pbb3', 'bbplus', 'Shot', 2, 3, null, 'fixed'),
    ],
    ratings: [
      mkRating('rbb1', 'bbplus', 4, 'Best value cocktails in Eixample'),
      mkRating('rbb2', 'bbplus', 4, 'Perfect pre-party before Sutton'),
    ],
    events: [], avg_rating: 4.1, rating_count: 2,
  },

  {
    id: 'lecyrano', name: 'Le Cyrano', type: 'previa',
    description: 'Iconic self-service bar on Aribau — you pour your own drink! The bartender hands you a bottle of spirit and a mixer for just €3. Gets packed fast, arrive before 11pm. Free popcorn included. A true Barcelona institution.',
    address: 'Carrer d\'Aribau, 154', neighborhood: 'Eixample',
    lat: 41.3903, lng: 2.1536,
    ambients: ['casual', 'indie'], music: ['Pop', 'Indie'],
    google_rating: 4.3, min_age: 18, dress_code: null,
    image_url: PHOTOS.vintageBar, website: null, instagram: '@lecyranobar', phone: null,
    opening_hours: { 'Thu–Sat': '22:30–02:30' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('pcy1', 'lecyrano', 'Entry', 0, null, null, 'free'),
      mkPrice('pcy2', 'lecyrano', 'Spirit + mixer (self-pour!)', 3, null, 'you pour your own', 'fixed'),
    ],
    ratings: [
      mkRating('rcy1', 'lecyrano', 5, 'Cheapest and most fun pre-party in BCN!'),
      mkRating('rcy2', 'lecyrano', 4, '€3 for a self-pour drink is unbeatable'),
    ],
    events: [], avg_rating: 4.3, rating_count: 2,
  },

  {
    id: '4latas', name: '4 Latas', type: 'previa',
    description: 'Lively tapas and cocktail bar chain with multiple locations across Barcelona. Live music, great cocktails and a party atmosphere. Multiple spots: Diagonal/Tuset, Letamendi, Granados, Poblenou. Perfect group pre-party.',
    address: 'Carrer de Tuset, 3 (also: Enric Granados 6 · Muntaner 211 · Poblenou)', neighborhood: 'Zona Alta',
    lat: 41.3970, lng: 2.1507,
    ambients: ['casual', 'pijo'], music: ['Pop', 'Latin', 'Reggaeton'],
    google_rating: 4.2, min_age: 18, dress_code: null,
    image_url: PHOTOS.casualBar, website: 'https://galeragroup.com/en/restaurants/barcelona/4-latas/', instagram: '@4latasbcn', phone: null,
    opening_hours: { 'Mon–Thu': '12:00–02:00', 'Fri–Sat': '12:00–03:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('p4l1', '4latas', 'Entry', 0, null, null, 'free'),
      mkPrice('p4l2', '4latas', 'Cocktail', 9, 12, null, 'fixed'),
      mkPrice('p4l3', '4latas', 'Shot', 3, 4, null, 'fixed'),
      mkPrice('p4l4', '4latas', 'Tapa', 4, 7, null, 'fixed'),
    ],
    ratings: [
      mkRating('r4l1', '4latas', 4, 'Great tapas + cocktails combo'),
      mkRating('r4l2', '4latas', 4, 'Multiple locations, always a good vibe'),
    ],
    events: [], avg_rating: 4.2, rating_count: 2,
  },

  {
    id: 'previaaribau', name: 'La Previa Aribau', type: 'previa',
    description: 'High-energy pre-party bar on Carrer Aribau, steps from Le Cyrano. Open every night until 03:30. Capacity for 130 people. Modern interior, strong drinks and great music. One of the best-known pre-party spots in Eixample.',
    address: 'Carrer d\'Aribau, 132', neighborhood: 'Eixample',
    lat: 41.3897, lng: 2.1540,
    ambients: ['casual', 'indie'], music: ['Pop', 'Reggaeton', 'Hip-Hop'],
    google_rating: 4.2, min_age: 18, dress_code: null,
    image_url: PHOTOS.casualBar, website: 'https://lapreviaeventos.com/', instagram: '@lapreviaribau', phone: null,
    opening_hours: { 'Daily': '23:00–03:30' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('ppa1', 'previaaribau', 'Entry', 0, null, null, 'free'),
      mkPrice('ppa2', 'previaaribau', 'Cocktail', 8, 11, null, 'fixed'),
      mkPrice('ppa3', 'previaaribau', 'Shot', 3, 4, null, 'fixed'),
    ],
    ratings: [
      mkRating('rpa1', 'previaaribau', 4, 'Best pre-party on Aribau street'),
      mkRating('rpa2', 'previaaribau', 4, 'Always packed, great energy'),
    ],
    events: [], avg_rating: 4.2, rating_count: 2,
  },

  // ── NEW CLUBS ────────────────────────────────────────────────────────────────

  {
    id: 'laterrazza', name: 'La Terrrazza', type: 'discoteca',
    description: 'Open-air electronic club at Poble Espanyol on Montjuïc. Dancing under the stars every weekend from April to November since 1995. Stunning 1920s architecture and unique open-air festival atmosphere. A Barcelona electronic summer institution.',
    address: 'Av. Francesc Ferrer i Guàrdia, 13 (Poble Espanyol)', neighborhood: 'Montjuïc',
    lat: 41.3696, lng: 2.1496,
    ambients: ['electronica', 'casual'], music: ['Electronic', 'Techno', 'House'],
    google_rating: 4.1, min_age: 18, dress_code: null,
    image_url: PHOTOS.poolParty, website: 'https://laterrrazza.com', instagram: '@laterrrazza', phone: null,
    opening_hours: { 'Fri–Sat': '00:00–06:00 (Apr–Nov)' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('plt1', 'laterrazza', 'Entry (varies by event)', 20, 30, null, 'dynamic', 'fourvenues', 'https://laterrrazza.com'),
      mkPrice('plt2', 'laterrazza', 'Spirit / cocktail', 14, 18, null, 'fixed'),
    ],
    ratings: [mkRating('rlt1', 'laterrazza', 5, 'Dancing under the stars — unmissable'), mkRating('rlt2', 'laterrazza', 4, 'Best open-air club in Spain')],
    events: [], avg_rating: 4.1, rating_count: 2,
  },

  {
    id: 'bikini', name: 'Bikini Barcelona', type: 'discoteca',
    description: 'The oldest entertainment venue in Barcelona, open since 1953. Reference for Latin music and salsa. Hosts live concerts by national and international artists. Two rooms with different vibes. Over 70 years of nightlife history.',
    address: 'Avinguda Diagonal, 547', neighborhood: 'Les Corts',
    lat: 41.3877, lng: 2.1362,
    ambients: ['latin', 'casual'], music: ['Latin', 'Reggaeton', 'Pop', 'Soul'],
    google_rating: 4.1, min_age: 18, dress_code: null,
    image_url: PHOTOS.hiphopClub, website: 'https://bikinibcn.com', instagram: '@bikinibcn', phone: null,
    opening_hours: { 'Thu–Sun': 'from 23:00' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('pbk1', 'bikini', 'Entry + 1 drink', 10, 15, '1 drink', 'dynamic', 'fourvenues', 'https://bikinibcn.com'),
      mkPrice('pbk2', 'bikini', 'Spirit / cocktail', 10, 14, null, 'fixed'),
    ],
    ratings: [mkRating('rbk1', 'bikini', 4, '70 years of nightlife, still going strong'), mkRating('rbk2', 'bikini', 4, 'Best Latin club in BCN')],
    events: [], avg_rating: 4.1, rating_count: 2,
  },

  {
    id: 'moog', name: 'Moog Club', type: 'discoteca',
    description: 'Cult underground club in El Raval, open 365 days a year. Small intimate venue with minimal decor and maximum intensity. Main room dedicated to pure techno; Villarosa room does pop-rock. A reference for underground electronic music since the 90s.',
    address: "Carrer de l'Arc del Teatre, 3", neighborhood: 'El Raval',
    lat: 41.3783, lng: 2.1754,
    ambients: ['electronica', 'indie'], music: ['Techno', 'Electronic'],
    google_rating: 4.2, min_age: 18, dress_code: null,
    image_url: PHOTOS.technoClub, website: 'https://masimas.com/moog', instagram: '@moog_barcelona', phone: null,
    opening_hours: { 'Daily': '00:00–06:00' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('pmg1', 'moog', 'Entry', 8, 15, null, 'dynamic', 'fourvenues', 'https://masimas.com/moog'),
      mkPrice('pmg2', 'moog', 'Spirit / cocktail', 10, 13, null, 'fixed'),
    ],
    ratings: [mkRating('rmg1', 'moog', 5, 'Best underground techno club in BCN'), mkRating('rmg2', 'moog', 4, 'Open every single night of the year')],
    events: [], avg_rating: 4.2, rating_count: 2,
  },

  {
    id: 'inputhifi', name: 'INPUT High Fidelity', type: 'discoteca',
    description: 'Barcelona\'s most technically advanced techno club. State-of-the-art Funktion-One sound system and circular design with 360° LED screen. An immersive experience that blurs the line between sound and vision. International reference for electronic music.',
    address: 'Av. Francesc Ferrer i Guàrdia, 13 (Poble Espanyol)', neighborhood: 'Montjuïc',
    lat: 41.3697, lng: 2.1498,
    ambients: ['techno', 'electronica'], music: ['Techno', 'Electronic', 'House'],
    google_rating: 4.4, min_age: 18, dress_code: null,
    image_url: PHOTOS.technoClub, website: 'https://www.inputbcn.com', instagram: '@inputdanceclub', phone: null,
    opening_hours: { 'Fri–Sat': '00:00–12:00' },
    price_sync_url: 'https://www.inputbcn.com/agenda', price_sync_source: 'scraping', created_at: '2024-01-01',
    prices: [
      mkPrice('pinh1', 'inputhifi', 'Entry (varies by event)', 15, 25, null, 'dynamic', 'scraping', 'https://www.inputbcn.com'),
      mkPrice('pinh2', 'inputhifi', 'Spirit / cocktail', 13, 16, null, 'fixed'),
    ],
    ratings: [mkRating('rinh1', 'inputhifi', 5, 'Funktion-One sound is otherworldly'), mkRating('rinh2', 'inputhifi', 5, 'Best techno experience in Spain')],
    events: [], avg_rating: 4.4, rating_count: 2,
  },

  {
    id: 'boris', name: 'Boris Club', type: 'discoteca',
    description: 'The most exclusive electronic club in the upper part of Barcelona. Electronic music, elegance and impeccable sound in a selective setting. Avant-garde design, private areas and spectacular lighting. Meeting point for the Barcelona elite who love electronic music.',
    address: 'Carrer de Rosselló, 208', neighborhood: 'Eixample',
    lat: 41.3940, lng: 2.1555,
    ambients: ['pijo', 'electronica'], music: ['Electronic', 'Techno', 'House'],
    google_rating: 4.1, min_age: 18, dress_code: 'Smart elegant',
    image_url: PHOTOS.luxClub, website: null, instagram: '@boris.club', phone: null,
    opening_hours: { 'Thu–Sat': 'from 23:30' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('pbrs1', 'boris', 'Entry', 20, 35, null, 'dynamic', 'fourvenues'),
      mkPrice('pbrs2', 'boris', 'Spirit / cocktail', 16, 22, null, 'fixed'),
    ],
    ratings: [mkRating('rbrs1', 'boris', 4, 'Exclusive electronic club, incredible sound'), mkRating('rbrs2', 'boris', 4, 'The pijo electronic club')],
    events: [], avg_rating: 4.1, rating_count: 2,
  },

  {
    id: 'twenties', name: 'Twenties Barcelona', type: 'discoteca',
    description: 'Elegant club next to Boris Club in Eixample. Sophisticated atmosphere and selective crowd. Commercial and trendy music. More accessible alternative to the Zona Alta clubs without being as exclusive as Sutton or Bling Bling.',
    address: 'Carrer de Rosselló, 208', neighborhood: 'Eixample',
    lat: 41.3941, lng: 2.1556,
    ambients: ['pijo', 'casual'], music: ['Pop', 'R&B', 'Reggaeton'],
    google_rating: 4.0, min_age: 18, dress_code: 'Smart',
    image_url: PHOTOS.luxClub, website: null, instagram: '@twentiesbarcelona', phone: null,
    opening_hours: { 'Thu–Sat': 'from 23:30' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('ptw1', 'twenties', 'Entry', 15, 25, null, 'dynamic', 'fourvenues'),
      mkPrice('ptw2', 'twenties', 'Spirit / cocktail', 14, 18, null, 'fixed'),
    ],
    ratings: [mkRating('rtw1', 'twenties', 4, 'Great alternative to Sutton'), mkRating('rtw2', 'twenties', 4, 'Stylish crowd, good music')],
    events: [], avg_rating: 4.0, rating_count: 2,
  },

  {
    id: 'latinpalace', name: 'Latin Palace', type: 'discoteca',
    description: 'The former Danzatoria, reinvented as the big Latin club of the Zona Alta. Two dancefloors with hip hop and electronic music. Bachelor parties and large groups welcome. Specialised in Latin music: salsa, bachata, reggaeton and Caribbean sounds.',
    address: 'Avinguda Diagonal, 477', neighborhood: 'Zona Alta',
    lat: 41.3933, lng: 2.1402,
    ambients: ['latin', 'casual'], music: ['Latin', 'Reggaeton', 'Soul', 'Hip-Hop'],
    google_rating: 3.8, min_age: 18, dress_code: null,
    image_url: PHOTOS.hiphopClub, website: null, instagram: '@latinpalacebcn', phone: null,
    opening_hours: { 'Thu–Sat': 'from 23:00' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('plp1', 'latinpalace', 'Entry', 10, 20, null, 'dynamic', 'fourvenues'),
      mkPrice('plp2', 'latinpalace', 'Spirit / cocktail', 12, 15, null, 'fixed'),
    ],
    ratings: [mkRating('rlp1', 'latinpalace', 4, 'Best salsa and bachata club in BCN'), mkRating('rlp2', 'latinpalace', 3, 'Great for groups and bachelor parties')],
    events: [], avg_rating: 3.8, rating_count: 2,
  },

  {
    id: 'ku', name: 'Ku Barcelona', type: 'discoteca',
    description: 'Beach club with seafront terrace at the heart of the Olympic Port. Festive and international atmosphere. Part of the Vila Olímpica circuit alongside Opium, Shôko and CDLC. Perfect for summer nights with house and pop music.',
    address: 'Passeig Marítim de la Barceloneta, 42', neighborhood: 'Barceloneta',
    lat: 41.3857, lng: 2.1982,
    ambients: ['pijo', 'casual'], music: ['House', 'Pop', 'Electronic'],
    google_rating: 3.8, min_age: 18, dress_code: 'Smart casual',
    image_url: PHOTOS.beachClub, website: null, instagram: '@kubarcelonaofficial', phone: null,
    opening_hours: { 'Thu–Sun': '23:00–06:00' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('pku1', 'ku', 'Free entry (guest list)', 0, null, null, 'free_list'),
      mkPrice('pku2', 'ku', 'Entry at door', 15, 20, null, 'dynamic', 'fourvenues'),
      mkPrice('pku3', 'ku', 'Spirit / cocktail', 13, 16, null, 'fixed'),
    ],
    ratings: [mkRating('rku1', 'ku', 4, 'Classic Olympic Port beach club'), mkRating('rku2', 'ku', 3, 'Good for a summer night out')],
    events: [], avg_rating: 3.8, rating_count: 2,
  },

  {
    id: 'downtown', name: 'Downtown Barcelona', type: 'discoteca',
    description: 'Club at the Olympic Port with terrace and international crowd. Commercial music, pop and reggaeton. Very popular with tourists and young locals. Relaxed and festive atmosphere, ideal for a fun night of dancing without pretensions.',
    address: 'Passeig Marítim de la Barceloneta, 30', neighborhood: 'Barceloneta',
    lat: 41.3852, lng: 2.1970,
    ambients: ['casual', 'pop'], music: ['Pop', 'Reggaeton', 'R&B'],
    google_rating: 3.7, min_age: 18, dress_code: null,
    image_url: PHOTOS.beachClub, website: null, instagram: '@downtownbcn', phone: null,
    opening_hours: { 'Thu–Sun': '23:00–06:00' },
    price_sync_url: null, price_sync_source: 'fourvenues', created_at: '2024-01-01',
    prices: [
      mkPrice('pdt1', 'downtown', 'Free entry (guest list)', 0, null, null, 'free_list'),
      mkPrice('pdt2', 'downtown', 'Entry at door', 10, 20, null, 'dynamic', 'fourvenues'),
      mkPrice('pdt3', 'downtown', 'Spirit / cocktail', 12, 15, null, 'fixed'),
    ],
    ratings: [mkRating('rdt1', 'downtown', 3, 'Very touristy but fun'), mkRating('rdt2', 'downtown', 4, 'Good value for the Port Olímpic area')],
    events: [], avg_rating: 3.7, rating_count: 2,
  },

  // ── NEW BARS ─────────────────────────────────────────────────────────────────

  {
    id: 'plata', name: 'Plata Cocktail Bar', type: 'bar',
    description: 'Innovative cocktail bar in Eixample combining pop art, neon lights and signature mixology. Huge social media presence thanks to its photogenic aesthetic. Creative cocktail menu in a modern and vibrant atmosphere. Popular with a young and trendy crowd.',
    address: 'Carrer del Consell de Cent, 233', neighborhood: 'Eixample',
    lat: 41.3876, lng: 2.1572,
    ambients: ['casual', 'pop'], music: ['Pop', 'Electronic', 'Indie'],
    google_rating: 4.5, min_age: 18, dress_code: null,
    image_url: PHOTOS.cocktailBar, website: null, instagram: '@platacocktailbar', phone: null,
    opening_hours: { 'Thu–Sun': '19:00–02:30' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('pplt1', 'plata', 'Entry', 0, null, null, 'free'),
      mkPrice('pplt2', 'plata', 'Signature cocktail', 12, 16, null, 'fixed'),
    ],
    ratings: [mkRating('rplt1', 'plata', 5, 'Most instagrammable bar in BCN'), mkRating('rplt2', 'plata', 4, 'Creative cocktails, great vibes')],
    events: [], avg_rating: 4.5, rating_count: 2,
  },

  {
    id: 'bettyfords', name: "Betty Ford's", type: 'bar',
    description: 'Bohemian indie bar in El Born known for creative cocktails and craft beers. Pleasant terrace and lively atmosphere night after night. Popular with creative young locals and bohemians of the neighbourhood.',
    address: 'Carrer de Joaquín Costa, 56', neighborhood: 'El Born',
    lat: 41.3834, lng: 2.1765,
    ambients: ['indie', 'casual'], music: ['Indie', 'Rock', 'Pop'],
    google_rating: 4.3, min_age: 18, dress_code: null,
    image_url: PHOTOS.casualBar, website: null, instagram: '@bettyfords_bcn', phone: null,
    opening_hours: { 'Tue–Sun': '19:00–02:30' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('pbf1', 'bettyfords', 'Entry', 0, null, null, 'free'),
      mkPrice('pbf2', 'bettyfords', 'Cocktail', 8, 12, null, 'fixed'),
      mkPrice('pbf3', 'bettyfords', 'Craft beer', 4, 6, null, 'fixed'),
    ],
    ratings: [mkRating('rbf1', 'bettyfords', 4, 'Great indie bar, brilliant cocktails'), mkRating('rbf2', 'bettyfords', 4, 'Love the terrace in summer')],
    events: [], avg_rating: 4.3, rating_count: 2,
  },

  // ── NEW PRE-PARTY BARS ───────────────────────────────────────────────────────

  {
    id: 'barcanyete', name: 'Bar Cañete', type: 'previa',
    description: 'Modern high-quality tapas tavern in El Raval. Long bar counter with vibrant atmosphere and excellent cuisine. Ideal for tapas and wine before heading out. Highly praised by critics and locals alike. Sophisticated yet accessible.',
    address: 'Carrer de la Unió, 17', neighborhood: 'El Raval',
    lat: 41.3792, lng: 2.1700,
    ambients: ['casual', 'pijo'], music: ['Jazz', 'Soul'],
    google_rating: 4.5, min_age: 18, dress_code: null,
    image_url: PHOTOS.tapasBar, website: 'https://www.barcanyete.com', instagram: '@barcanyete', phone: null,
    opening_hours: { 'Tue–Sat': '13:00–24:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('pcan1', 'barcanyete', 'Entry', 0, null, null, 'free'),
      mkPrice('pcan2', 'barcanyete', 'Cocktail / wine', 8, 12, null, 'fixed'),
      mkPrice('pcan3', 'barcanyete', 'Tapa', 4, 9, null, 'fixed'),
    ],
    ratings: [mkRating('rcan1', 'barcanyete', 5, 'Best tapas in Barcelona, full stop'), mkRating('rcan2', 'barcanyete', 4, 'Perfect dinner before a big night')],
    events: [], avg_rating: 4.5, rating_count: 2,
  },

  {
    id: 'morrofi', name: 'Morro Fi', type: 'previa',
    description: 'Modern vermuteria bar in Sant Antoni, popular for great vermouths, cocktails and neighbourhood atmosphere. Ideal for a long and relaxed pre-party. Very popular with young locals. Lively terrace on weekends.',
    address: 'Carrer del Consell de Cent, 171', neighborhood: 'Sant Antoni',
    lat: 41.3810, lng: 2.1578,
    ambients: ['casual', 'indie'], music: ['Indie', 'Pop', 'Electronic'],
    google_rating: 4.3, min_age: 18, dress_code: null,
    image_url: PHOTOS.casualBar, website: null, instagram: '@morrofi_bcn', phone: null,
    opening_hours: { 'Tue–Sun': '10:00–02:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('pmf1', 'morrofi', 'Entry', 0, null, null, 'free'),
      mkPrice('pmf2', 'morrofi', 'Vermouth / cocktail', 7, 10, null, 'fixed'),
      mkPrice('pmf3', 'morrofi', 'Shot', 3, 4, null, 'fixed'),
    ],
    ratings: [mkRating('rmf1', 'morrofi', 4, 'Best vermouth in Sant Antoni'), mkRating('rmf2', 'morrofi', 4, 'Great neighbourhood vibe')],
    events: [], avg_rating: 4.3, rating_count: 2,
  },

  {
    id: 'bodegasepulveda', name: 'Bodega Sepúlveda', type: 'previa',
    description: 'Wine and vermouth bar with great atmosphere in Sant Antoni. Open all day, ideal for long aperitivos and lively pre-parties. Popular with young locals. Part of the Parlament Street bar circuit. Authentic bodega converted into a modern bar.',
    address: 'Carrer de Sepúlveda, 173', neighborhood: 'Sant Antoni',
    lat: 41.3815, lng: 2.1593,
    ambients: ['casual', 'indie'], music: ['Indie', 'Rock', 'Pop'],
    google_rating: 4.5, min_age: 18, dress_code: null,
    image_url: PHOTOS.vintageBar, website: null, instagram: '@bodegasepulveda', phone: null,
    opening_hours: { 'Daily': '10:00–02:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('pbs1', 'bodegasepulveda', 'Entry', 0, null, null, 'free'),
      mkPrice('pbs2', 'bodegasepulveda', 'Wine / cocktail', 6, 9, null, 'fixed'),
      mkPrice('pbs3', 'bodegasepulveda', 'Shot', 2, 4, null, 'fixed'),
    ],
    ratings: [mkRating('rbs1', 'bodegasepulveda', 5, 'Best natural wine bar in the neighbourhood'), mkRating('rbs2', 'bodegasepulveda', 4, 'Always a great atmosphere')],
    events: [], avg_rating: 4.5, rating_count: 2,
  },

  // ── NEW RESTAURANTS ──────────────────────────────────────────────────────────

  {
    id: 'nuba', name: 'Nuba Barcelona', type: 'restaurant',
    description: 'Zona Alta classic where the restaurant slowly transforms into a club as the night progresses. Live DJs, international author menus and quality cocktails. Seductive terrace and exclusive atmosphere. Open Wed–Sun.',
    address: 'Carrer de Granja Elena, 1', neighborhood: 'Zona Alta',
    lat: 41.4003, lng: 2.1428,
    ambients: ['pijo', 'casual'], music: ['Electronic', 'Hip-Hop', 'House'],
    google_rating: 4.1, min_age: 18, dress_code: 'Smart',
    image_url: PHOTOS.luxRestau, website: null, instagram: '@nuba_bcn', phone: null,
    opening_hours: { 'Wed–Sun': '20:00–03:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('pnb1', 'nuba', 'Dinner per person', 35, 55, 'food only', 'fixed'),
      mkPrice('pnb2', 'nuba', 'Club entry (after dinner)', 15, 20, null, 'dynamic', 'fourvenues'),
      mkPrice('pnb3', 'nuba', 'Cocktail', 14, 18, null, 'fixed'),
    ],
    ratings: [mkRating('rnb1', 'nuba', 4, 'Best restaurant-to-club transition in BCN'), mkRating('rnb2', 'nuba', 4, 'Dinner + party in one place')],
    events: [], avg_rating: 4.1, rating_count: 2,
  },

  {
    id: 'bravo', name: 'Bravo (Hotel W)', type: 'restaurant',
    description: 'Mediterranean restaurant at Hotel W Barcelona with spectacular sea views. Barcelona tapas with local quality produce and grilled dishes. Perfect for a luxury dinner with sea views before continuing at the Wet Deck or Noxe. Premium atmosphere.',
    address: 'Plaça de la Rosa dels Vents, 1 (Hotel W)', neighborhood: 'Barceloneta',
    lat: 41.3721, lng: 2.1783,
    ambients: ['pijo'], music: ['House', 'Pop', 'Electronic'],
    google_rating: 4.2, min_age: 0, dress_code: 'Smart',
    image_url: PHOTOS.luxRestau, website: null, instagram: '@bravowbarcelona', phone: null,
    opening_hours: { 'Daily': '13:00–23:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('pbrv1', 'bravo', 'Dinner per person', 50, 90, 'food only', 'fixed'),
      mkPrice('pbrv2', 'bravo', 'Cocktail', 16, 22, null, 'fixed'),
    ],
    ratings: [mkRating('rbrv1', 'bravo', 4, 'Best sea view dinner in Barcelona'), mkRating('rbrv2', 'bravo', 5, 'Perfect before Noxe on floor 26')],
    events: [], avg_rating: 4.2, rating_count: 2,
  },

  {
    id: 'mareaalta', name: 'Marea Alta', type: 'restaurant',
    description: 'Fish and seafood restaurant on floor 24 of Torre Colón with 360° panoramic views over Barcelona and the Mediterranean. Daily-changing menu with the best seasonal fish. Elegant and exclusive, ideal for a special dinner. Saturday midday Mimosa Party.',
    address: 'Avinguda de les Drassanes, 6 (Torre Colón, floor 24)', neighborhood: 'Barri Gòtic',
    lat: 41.3768, lng: 2.1793,
    ambients: ['pijo'], music: ['Jazz', 'Soul', 'House'],
    google_rating: 4.3, min_age: 0, dress_code: 'Smart elegant',
    image_url: PHOTOS.rooftop, website: null, instagram: '@mareaaltabcn', phone: null,
    opening_hours: { 'Tue–Sun': '13:00–23:30' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('pma1', 'mareaalta', 'Dinner per person', 55, 90, 'food only', 'fixed'),
      mkPrice('pma2', 'mareaalta', 'Cocktail', 15, 20, null, 'fixed'),
    ],
    ratings: [mkRating('rma1', 'mareaalta', 5, '360° views + incredible fish — perfect evening'), mkRating('rma2', 'mareaalta', 4, 'Saturday Mimosa Party is a must')],
    events: [], avg_rating: 4.3, rating_count: 2,
  },

  {
    id: 'wetdeck', name: 'Wet Deck (Hotel W)', type: 'restaurant',
    description: "Barcelona's most exclusive pool terrace, at Hotel W. Centre of attention every summer with Sunday Wet Deck Summer Series. DJs, dancers, fireworks and sea views. High-quality snacks and cocktails menu. Ibiza-meets-Barcelona atmosphere.",
    address: 'Plaça de la Rosa dels Vents, 1 (Hotel W, terrace)', neighborhood: 'Barceloneta',
    lat: 41.3722, lng: 2.1784,
    ambients: ['pijo', 'casual'], music: ['House', 'Electronic', 'Pop'],
    google_rating: 4.2, min_age: 18, dress_code: 'Smart casual',
    image_url: PHOTOS.poolParty, website: null, instagram: '@wetdeckbarcelona', phone: null,
    opening_hours: { 'Fri–Sun': '12:00–21:00 (seasonal)' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('pwd1', 'wetdeck', 'Entry (minimum spend)', 0, null, 'min. consumption required', 'free'),
      mkPrice('pwd2', 'wetdeck', 'Cocktail', 16, 22, null, 'fixed'),
    ],
    ratings: [mkRating('rwd1', 'wetdeck', 5, 'Best pool party in Barcelona by far'), mkRating('rwd2', 'wetdeck', 4, 'Sunday sessions are incredible')],
    events: [], avg_rating: 4.2, rating_count: 2,
  },

  {
    id: 'mood', name: 'Mood Rooftop', type: 'restaurant',
    description: 'Rooftop bar-restaurant with panoramic city views. Mediterranean cuisine with fresh ingredients, creative cocktails and sophisticated atmosphere. Live jazz and hip-hop music on some evenings. Very popular for afternoon sessions and special dinners.',
    address: 'Gran Via de les Corts Catalanes, 616 (Hotel Gallery)', neighborhood: 'Eixample',
    lat: 41.3895, lng: 2.1608,
    ambients: ['pijo', 'casual'], music: ['Jazz', 'Hip-Hop', 'House'],
    google_rating: 4.3, min_age: 0, dress_code: null,
    image_url: PHOTOS.rooftop, website: null, instagram: '@moodrooftopbcn', phone: null,
    opening_hours: { 'Tue–Sun': '12:00–00:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('pmd1', 'mood', 'Dinner per person', 35, 55, 'food only', 'fixed'),
      mkPrice('pmd2', 'mood', 'Cocktail', 14, 18, null, 'fixed'),
    ],
    ratings: [mkRating('rmd1', 'mood', 4, 'Stunning views, great cocktails'), mkRating('rmd2', 'mood', 4, 'Perfect for a special occasion')],
    events: [], avg_rating: 4.3, rating_count: 2,
  },

  {
    id: 'gobeach', name: 'Go Beach Club', type: 'restaurant',
    description: 'Beach club with restaurant, pool and live music sessions. Singing and dancing shows during dinner, then nightclub after. 1920s decor. Ideal for groups combining dinner and a party in one place. Part of the Sea Sea complex.',
    address: 'Rambla Prim, 17 (Port Fòrum)', neighborhood: 'Fòrum',
    lat: 41.4101, lng: 2.2251,
    ambients: ['casual', 'pijo'], music: ['House', 'Electronic', 'Pop'],
    google_rating: 3.9, min_age: 0, dress_code: null,
    image_url: PHOTOS.beachClub, website: null, instagram: '@gobeachclub_bcn', phone: null,
    opening_hours: { 'Thu–Sun': '20:00–03:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('pgb1', 'gobeach', 'Dinner per person', 30, 50, 'food only', 'fixed'),
      mkPrice('pgb2', 'gobeach', 'Cocktail', 13, 17, null, 'fixed'),
    ],
    ratings: [mkRating('rgb1', 'gobeach', 4, 'Great dinner + show concept'), mkRating('rgb2', 'gobeach', 4, 'Fun group venue')],
    events: [], avg_rating: 3.9, rating_count: 2,
  },

  {
    id: 'sohohouse', name: 'Soho House Barcelona', type: 'restaurant',
    description: 'International private members club with restaurant and rooftop pool bar with exceptional views. The upper floors offer quality cocktails, Italian food and sea-and-city views. Restaurant open to all; rooftop exclusive to members. Creative and sophisticated crowd.',
    address: 'Plaça de Catalunya, 10', neighborhood: 'Eixample',
    lat: 41.3870, lng: 2.1694,
    ambients: ['pijo', 'indie'], music: ['Indie', 'Soul', 'Jazz'],
    google_rating: 4.3, min_age: 18, dress_code: 'Smart casual',
    image_url: PHOTOS.rooftop, website: 'https://www.sohohouse.com/en-us/houses/soho-house-barcelona', instagram: '@sohohousebarcelona', phone: null,
    opening_hours: { 'Daily': '12:00–00:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('psh1', 'sohohouse', 'Dinner per person', 40, 70, 'food only', 'fixed'),
      mkPrice('psh2', 'sohohouse', 'Cocktail', 15, 20, null, 'fixed'),
    ],
    ratings: [mkRating('rsh1', 'sohohouse', 4, 'Incredibly stylish, great creative crowd'), mkRating('rsh2', 'sohohouse', 5, 'Rooftop pool on a summer evening is unbeatable')],
    events: [], avg_rating: 4.3, rating_count: 2,
  },

  {
    id: 'elguzzo', name: 'El Guzzo', type: 'restaurant',
    description: 'El Born restaurant with live jazz, blues and soul concerts every night. Creative Mediterranean cuisine and excellent wine selection. One of the best places in Barcelona to combine a quality dinner with live music. Bohemian and authentic atmosphere.',
    address: 'Carrer dels Flassaders, 49', neighborhood: 'El Born',
    lat: 41.3839, lng: 2.1810,
    ambients: ['casual', 'soul'], music: ['Jazz', 'Soul', 'Rock'],
    google_rating: 4.4, min_age: 0, dress_code: null,
    image_url: PHOTOS.jazzClub, website: null, instagram: '@elguzzo_bcn', phone: null,
    opening_hours: { 'Tue–Sat': '20:00–00:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('peg1', 'elguzzo', 'Dinner per person', 30, 45, 'food + show', 'fixed'),
      mkPrice('peg2', 'elguzzo', 'Cocktail', 10, 14, null, 'fixed'),
    ],
    ratings: [mkRating('reg1', 'elguzzo', 5, 'Live jazz every night — magical'), mkRating('reg2', 'elguzzo', 4, 'Best dinner with live music in BCN')],
    events: [], avg_rating: 4.4, rating_count: 2,
  },

  {
    id: 'salamilano', name: 'Sala Milano', type: 'restaurant',
    description: 'Classic restaurant with live jazz shows. Jazz menu from €29 includes concert. Quality Italian and Mediterranean cuisine. The perfect option for an elegant dinner with live music. Elegant and nostalgic atmosphere. A true Barcelona classic since the 1950s.',
    address: 'Ronda de la Universitat, 35', neighborhood: 'Eixample',
    lat: 41.3876, lng: 2.1660,
    ambients: ['pijo', 'soul'], music: ['Jazz', 'Soul'],
    google_rating: 4.2, min_age: 0, dress_code: 'Smart',
    image_url: PHOTOS.jazzClub, website: null, instagram: '@salamilano_bcn', phone: null,
    opening_hours: { 'Tue–Sat': '20:00–00:00' },
    price_sync_url: null, price_sync_source: null, created_at: '2024-01-01',
    prices: [
      mkPrice('psm1', 'salamilano', 'Jazz menu (dinner + concert)', 29, 45, 'dinner + live show', 'fixed'),
      mkPrice('psm2', 'salamilano', 'Cocktail', 10, 14, null, 'fixed'),
    ],
    ratings: [mkRating('rsm1', 'salamilano', 4, 'Jazz dinner concept is genius'), mkRating('rsm2', 'salamilano', 4, 'A real Barcelona classic')],
    events: [], avg_rating: 4.2, rating_count: 2,
  },
]
