import type { VenueWithDetails } from '@/types'

export const mockVenues: VenueWithDetails[] = [
  // ─── EXISTING VENUES ────────────────────────────────────────────────────────
  {
    id: '1',
    name: 'Opium Barcelona',
    type: 'discoteca',
    description: 'Iconic beachfront club at the Olympic Port with terrace and sea views.',
    address: 'Passeig Marítim de la Barceloneta, 34',
    neighborhood: 'Barceloneta',
    lat: 41.3854,
    lng: 2.1974,
    ambients: ['pijo', 'pop'],
    min_age: 18,
    dress_code: null,
    image_url: null,
    website: 'https://www.opiumbarcelona.com',
    instagram: '@opiumbarcelona',
    phone: null,
    opening_hours: { 'Thu–Sat': '23:00–06:00' },
    price_sync_url: null,
    price_sync_source: null,
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p1', venue_id: '1', label: 'Entry + 1 drink', amount: 20, amount_max: null,
        currency: 'EUR', includes: '1 drink', entrada_tipus: 'fixed', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
    ],
    ratings: [
      { id: 'r1', venue_id: '1', user_id: null, score: 4, comment: 'Great atmosphere!', ambients: ['pijo'], created_at: '2024-01-01' },
      { id: 'r2', venue_id: '1', user_id: null, score: 3, comment: 'Too packed on weekends', ambients: ['pop'], created_at: '2024-01-01' },
    ],
    events: [],
    avg_rating: 3.5,
    rating_count: 2,
  },
  {
    id: '2',
    name: 'Razzmatazz',
    type: 'discoteca',
    description: '5 rooms, 5 sounds: rock, electronic, indie and more. BCN\'s best alternative club.',
    address: 'Carrer dels Almogàvers, 122',
    neighborhood: 'Poblenou',
    lat: 41.4009,
    lng: 2.1972,
    ambients: ['indie', 'electronica', 'rock'],
    min_age: 18,
    dress_code: null,
    image_url: null,
    website: 'https://www.salarazzmatazz.com',
    instagram: '@razzmatazz',
    phone: null,
    opening_hours: { 'Thu–Sat': '01:00–06:00' },
    price_sync_url: null,
    price_sync_source: null,
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p2', venue_id: '2', label: 'General entry', amount: 15, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'fixed', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
    ],
    ratings: [
      { id: 'r3', venue_id: '2', user_id: null, score: 5, comment: 'Best in BCN for indie/electro', ambients: ['indie', 'electronica'], created_at: '2024-01-01' },
    ],
    events: [
      {
        id: 'e1', venue_id: '2', name: 'Electronic Night', date: '2026-06-07',
        doors_open: '01:00', price_min: 12, price_max: 18, currency: 'EUR',
        ticket_url: 'https://www.salarazzmatazz.com', artists: ['DJ Snake', 'Bicep'],
        genre: 'electronica', source_id: null, source: 'manual', created_at: '2024-01-01',
      },
    ],
    avg_rating: 5,
    rating_count: 1,
  },
  {
    id: '4',
    name: 'Input Dance Club',
    type: 'discoteca',
    description: 'Temple of underground techno and electronic music in Barcelona.',
    address: 'Carrer de Gran Via de les Corts Catalanes, 235',
    neighborhood: 'Sants',
    lat: 41.3748,
    lng: 2.1378,
    ambients: ['techno', 'electronica'],
    min_age: 18,
    dress_code: null,
    image_url: null,
    website: 'https://www.inputbcn.com',
    instagram: '@inputbcn',
    phone: null,
    opening_hours: { 'Sat–Sun': '00:00–12:00' },
    price_sync_url: null,
    price_sync_source: null,
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p4', venue_id: '4', label: 'Entry', amount: 18, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'fixed', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'residentadvisor', created_at: '2024-01-01',
      },
    ],
    ratings: [
      { id: 'r5', venue_id: '4', user_id: null, score: 5, comment: 'Incredible sound system, best in BCN', ambients: ['techno'], created_at: '2024-01-01' },
      { id: 'r6', venue_id: '4', user_id: null, score: 4, comment: 'Underground and authentic', ambients: ['electronica'], created_at: '2024-01-01' },
    ],
    events: [],
    avg_rating: 4.5,
    rating_count: 2,
  },
  {
    id: '5',
    name: 'Macarena Club',
    type: 'discoteca',
    description: 'A hidden gem in the Gothic Quarter. Reggaeton and Latin music all night long.',
    address: 'Carrer Nou de Sant Francesc, 5',
    neighborhood: 'Barri Gòtic',
    lat: 41.3797,
    lng: 2.1766,
    ambients: ['reggaeton', 'latin'],
    min_age: 18,
    dress_code: null,
    image_url: null,
    website: null,
    instagram: '@macarenaclub',
    phone: null,
    opening_hours: { 'Daily': '00:00–05:00' },
    price_sync_url: null,
    price_sync_source: null,
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p5', venue_id: '5', label: 'Free entry', amount: 0, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
    ],
    ratings: [
      { id: 'r7', venue_id: '5', user_id: null, score: 4, comment: 'Very intimate and good vibes', ambients: ['reggaeton'], created_at: '2024-01-01' },
    ],
    events: [],
    avg_rating: 4,
    rating_count: 1,
  },
  {
    id: '6',
    name: 'Bar Marsella',
    type: 'bar',
    description: 'The oldest bar in Barcelona (1820). Absinthe and classic cocktails in a unique atmosphere.',
    address: 'Carrer dels Escudellers Blancs, 3',
    neighborhood: 'Barri Gòtic',
    lat: 41.3797,
    lng: 2.1748,
    ambients: ['indie', 'casual'],
    min_age: 18,
    dress_code: null,
    image_url: null,
    website: null,
    instagram: null,
    phone: null,
    opening_hours: { 'Mon–Sat': '22:00–02:00' },
    price_sync_url: null,
    price_sync_source: null,
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p6', venue_id: '6', label: 'Average drink', amount: 8, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
    ],
    ratings: [
      { id: 'r8', venue_id: '6', user_id: null, score: 5, comment: 'Unique place, a must-visit!', ambients: ['indie'], created_at: '2024-01-01' },
    ],
    events: [],
    avg_rating: 5,
    rating_count: 1,
  },
  {
    id: '9',
    name: 'La Pepita BCN',
    type: 'restaurant',
    description: 'Typical Barcelona patatas bravas and croquettes. Casual and quality dinner spot.',
    address: 'Carrer de Còrsega, 343',
    neighborhood: 'Eixample',
    lat: 41.3984,
    lng: 2.1631,
    ambients: ['casual', 'indie'],
    min_age: 0,
    dress_code: null,
    image_url: null,
    website: null,
    instagram: null,
    phone: null,
    opening_hours: { 'Daily': '13:00–23:30' },
    price_sync_url: null,
    price_sync_source: null,
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p9', venue_id: '9', label: 'Dinner per person', amount: 20, amount_max: null,
        currency: 'EUR', includes: 'food and drinks', entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
    ],
    ratings: [],
    events: [],
    avg_rating: 0,
    rating_count: 0,
  },

  // ─── PRE-PARTY BARS ──────────────────────────────────────────────────────────
  {
    id: '10',
    name: 'La Previa',
    type: 'previa',
    description: 'Lively pre-party bar in Poblenou with live DJs playing current hits. Young, mixed crowd — perfect before heading to Razzmatazz or Wolf.',
    address: 'Carrer de Pallars, Barcelona',
    neighborhood: 'Poblenou',
    lat: 41.4013,
    lng: 2.1950,
    ambients: ['pop', 'reggaeton', 'casual'],
    min_age: 18,
    dress_code: null,
    image_url: null,
    website: null,
    instagram: null,
    phone: null,
    opening_hours: { 'Daily': '23:00–03:30' },
    price_sync_url: null,
    price_sync_source: null,
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p10a', venue_id: '10', label: 'Entry', amount: 0, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
      {
        id: 'p10b', venue_id: '10', label: 'Cubata (spirit + mixer)', amount: 7, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
      {
        id: 'p10c', venue_id: '10', label: 'Beer', amount: 4, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
      {
        id: 'p10d', venue_id: '10', label: 'Cocktail', amount: 8, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
    ],
    ratings: [
      { id: 'r10', venue_id: '10', user_id: null, score: 5, comment: 'Best pre-party spot in Poblenou', ambients: ['pop'], created_at: '2024-01-01' },
      { id: 'r10b', venue_id: '10', user_id: null, score: 4, comment: 'Great vibe, affordable drinks', ambients: ['casual'], created_at: '2024-01-01' },
    ],
    events: [],
    avg_rating: 4.7,
    rating_count: 2,
  },
  {
    id: '11',
    name: "L'Ovella Negra (Marina)",
    type: 'previa',
    description: 'University-favourite tavern near Razzmatazz — perfect pre-party for big groups. Relaxed vibe, cheap pitchers and sangria.',
    address: 'Carrer dels Almogàvers, Poblenou',
    neighborhood: 'Poblenou',
    lat: 41.4007,
    lng: 2.1960,
    ambients: ['casual', 'indie'],
    min_age: 18,
    dress_code: null,
    image_url: null,
    website: null,
    instagram: null,
    phone: null,
    opening_hours: { 'Daily': 'until 03:00' },
    price_sync_url: null,
    price_sync_source: null,
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p11a', venue_id: '11', label: 'Entry', amount: 0, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
      {
        id: 'p11b', venue_id: '11', label: 'Beer pitcher', amount: 6, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
      {
        id: 'p11c', venue_id: '11', label: 'Sangria', amount: 5, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
      {
        id: 'p11d', venue_id: '11', label: 'Tapa', amount: 3, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
    ],
    ratings: [
      { id: 'r11', venue_id: '11', user_id: null, score: 4, comment: 'Super cheap, great for groups before Razzmatazz', ambients: ['casual'], created_at: '2024-01-01' },
      { id: 'r11b', venue_id: '11', user_id: null, score: 4, comment: 'Classic student spot', ambients: ['indie'], created_at: '2024-01-01' },
    ],
    events: [],
    avg_rating: 4.2,
    rating_count: 2,
  },
  {
    id: '12',
    name: "L'Ovella Negra (Sitges)",
    type: 'previa',
    description: 'Iconic low-cost tavern in El Raval. Tourist-friendly, mixed crowd, great budget pre-party.',
    address: 'Carrer de Sitges, 5',
    neighborhood: 'El Raval',
    lat: 41.3806,
    lng: 2.1681,
    ambients: ['casual'],
    min_age: 18,
    dress_code: null,
    image_url: null,
    website: null,
    instagram: null,
    phone: null,
    opening_hours: { 'Daily': 'until 03:00' },
    price_sync_url: null,
    price_sync_source: null,
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p12a', venue_id: '12', label: 'Entry', amount: 0, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
      {
        id: 'p12b', venue_id: '12', label: 'Beer', amount: 3, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
      {
        id: 'p12c', venue_id: '12', label: 'Cocktail', amount: 6, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
    ],
    ratings: [
      { id: 'r12', venue_id: '12', user_id: null, score: 4, comment: 'Unbeatable prices in the city centre', ambients: ['casual'], created_at: '2024-01-01' },
    ],
    events: [],
    avg_rating: 4.0,
    rating_count: 1,
  },
  {
    id: '13',
    name: 'BB+',
    type: 'previa',
    description: 'Young, university crowd pre-party bar in the Eixample. Affordable drinks and social atmosphere.',
    address: 'Eixample, Barcelona',
    neighborhood: 'Eixample',
    lat: 41.3930,
    lng: 2.1580,
    ambients: ['pop', 'casual'],
    min_age: 18,
    dress_code: null,
    image_url: null,
    website: null,
    instagram: null,
    phone: null,
    opening_hours: { 'Daily': 'evenings' },
    price_sync_url: null,
    price_sync_source: null,
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p13', venue_id: '13', label: 'Entry', amount: 0, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
    ],
    ratings: [],
    events: [],
    avg_rating: 0,
    rating_count: 0,
  },
  {
    id: '14',
    name: 'Le Cyrano',
    type: 'previa',
    description: 'Upscale cocktail bar — the go-to pre-party for a pijo crowd. Sophisticated atmosphere and quality drinks before heading to Sutton or Bling Bling.',
    address: 'Barcelona',
    neighborhood: 'Eixample',
    lat: 41.3960,
    lng: 2.1565,
    ambients: ['pijo', 'casual'],
    min_age: 18,
    dress_code: 'Smart casual',
    image_url: null,
    website: null,
    instagram: null,
    phone: null,
    opening_hours: { 'Daily': 'evenings' },
    price_sync_url: null,
    price_sync_source: null,
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p14', venue_id: '14', label: 'Entry', amount: 0, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
    ],
    ratings: [],
    events: [],
    avg_rating: 0,
    rating_count: 0,
  },

  // ─── CLUBS ───────────────────────────────────────────────────────────────────
  {
    id: '15',
    name: 'Sutton',
    type: 'discoteca',
    description: 'Exclusive club on Carrer Tuset. Elegant dress code strictly enforced. Reggaeton, hip-hop and R&B for an international upscale crowd. VIP tables from €300.',
    address: 'Carrer de Tuset, Zona Alta',
    neighborhood: 'Gràcia Alta',
    lat: 41.3974,
    lng: 2.1504,
    ambients: ['pijo', 'reggaeton', 'hiphop', 'rnb'],
    min_age: 23,
    dress_code: 'Elegant — strictly enforced',
    image_url: null,
    website: 'https://www.thesuttonclub.com',
    instagram: '@suttonbcn',
    phone: null,
    opening_hours: { 'Thu–Sat': '23:30–06:00' },
    price_sync_url: null,
    price_sync_source: null,
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p15a', venue_id: '15', label: 'Entry + 1 drink', amount: 15, amount_max: 20,
        currency: 'EUR', includes: '1 drink', entrada_tipus: 'dynamic', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: '2026-06-02T00:00:00Z',
        source: 'manual', created_at: '2024-01-01',
      },
      {
        id: 'p15b', venue_id: '15', label: 'Cocktail / spirit', amount: 12, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
      {
        id: 'p15c', venue_id: '15', label: 'Soft drink', amount: 4, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
      {
        id: 'p15d', venue_id: '15', label: 'VIP table minimum', amount: 300, amount_max: null,
        currency: 'EUR', includes: 'bottle service', entrada_tipus: 'fixed', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
    ],
    ratings: [
      { id: 'r15', venue_id: '15', user_id: null, score: 5, comment: 'Top pijo club, great music and crowd', ambients: ['pijo', 'reggaeton'], created_at: '2024-01-01' },
      { id: 'r15b', venue_id: '15', user_id: null, score: 4, comment: 'Worth it if you have the budget', ambients: ['hiphop'], created_at: '2024-01-01' },
    ],
    events: [],
    avg_rating: 4.5,
    rating_count: 2,
  },
  {
    id: '16',
    name: 'Bling Bling',
    type: 'discoteca',
    description: 'Selective upscale club on Tuset. Reggaeton and commercial house. Thu 18+, Fri–Sat 23+ only.',
    address: 'Carrer de Tuset, 8–10',
    neighborhood: 'Sarrià-Sant Gervasi',
    lat: 41.3971,
    lng: 2.1498,
    ambients: ['pijo', 'reggaeton', 'house'],
    min_age: 18,
    dress_code: 'Smart — selective entry',
    image_url: null,
    website: null,
    instagram: '@blingblingbcn',
    phone: null,
    opening_hours: { 'Wed–Sat': 'from 23:00' },
    price_sync_url: null,
    price_sync_source: 'fourvenues',
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p16', venue_id: '16', label: 'Entry + 1 drink', amount: 20, amount_max: null,
        currency: 'EUR', includes: '1 drink', entrada_tipus: 'dynamic', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: '2026-06-02T00:00:00Z',
        source: 'fourvenues', created_at: '2024-01-01',
      },
    ],
    ratings: [
      { id: 'r16', venue_id: '16', user_id: null, score: 4, comment: 'Selective but fun once you\'re in', ambients: ['pijo'], created_at: '2024-01-01' },
      { id: 'r16b', venue_id: '16', user_id: null, score: 4, comment: 'Good reggaeton night on Fridays', ambients: ['reggaeton'], created_at: '2024-01-01' },
    ],
    events: [],
    avg_rating: 4.2,
    rating_count: 2,
  },
  {
    id: '17',
    name: 'Otto Zutz',
    type: 'discoteca',
    description: '3-floor club: Room 1 Reggaeton & hits / Room 2 House & pop / Room 3 Hip-hop & R&B. International selective crowd.',
    address: 'Carrer de Lincoln, 15',
    neighborhood: 'Sarrià-Sant Gervasi',
    lat: 41.4005,
    lng: 2.1430,
    ambients: ['reggaeton', 'house', 'hiphop', 'pop'],
    min_age: 18,
    dress_code: 'Smart — selective entry',
    image_url: null,
    website: null,
    instagram: '@ottozotz',
    phone: null,
    opening_hours: { 'Thu–Sat': 'from 23:30' },
    price_sync_url: null,
    price_sync_source: 'fourvenues',
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p17a', venue_id: '17', label: 'Free entry (guest list)', amount: 0, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free_list', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
      {
        id: 'p17b', venue_id: '17', label: 'Entry without guest list', amount: 15, amount_max: 20,
        currency: 'EUR', includes: null, entrada_tipus: 'dynamic', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: '2026-06-02T00:00:00Z',
        source: 'fourvenues', created_at: '2024-01-01',
      },
      {
        id: 'p17c', venue_id: '17', label: 'Cocktail / spirit', amount: 12, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
    ],
    ratings: [
      { id: 'r17', venue_id: '17', user_id: null, score: 4, comment: 'Three floors, something for everyone', ambients: ['reggaeton', 'hiphop'], created_at: '2024-01-01' },
    ],
    events: [],
    avg_rating: 4.1,
    rating_count: 1,
  },
  {
    id: '18',
    name: 'Luz de Gas',
    type: 'discoteca',
    description: 'Concert hall and club inside a stunning rococo theatre. Soul, jazz, rock and R&B. Mature, upscale crowd. Entry price varies by event — auto-synced from luzdegas.com.',
    address: 'Carrer de Muntaner, 246',
    neighborhood: 'Zona Alta',
    lat: 41.3956,
    lng: 2.1473,
    ambients: ['soul', 'jazz', 'rock', 'rnb', 'pijo'],
    min_age: 18,
    dress_code: 'Smart casual',
    image_url: null,
    website: 'https://www.luzdegas.com',
    instagram: '@luzdegas',
    phone: null,
    opening_hours: { 'Wed–Sun': '23:30–05:00', 'Fri–Sat': 'until 06:00' },
    price_sync_url: 'https://www.luzdegas.com/agenda',
    price_sync_source: 'scraping',
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p18', venue_id: '18', label: 'Entry + 1 drink (varies by event)',
        amount: 15, amount_max: 20,
        currency: 'EUR', includes: '1 drink', entrada_tipus: 'dynamic', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: '2026-06-02T00:00:00Z',
        source: 'scraping', created_at: '2024-01-01',
      },
      {
        id: 'p18b', venue_id: '18', label: 'Beer', amount: 7, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
    ],
    ratings: [
      { id: 'r18', venue_id: '18', user_id: null, score: 4, comment: 'Stunning venue, great soul nights', ambients: ['soul', 'jazz'], created_at: '2024-01-01' },
      { id: 'r18b', venue_id: '18', user_id: null, score: 5, comment: 'Most beautiful club in Barcelona', ambients: ['pijo'], created_at: '2024-01-01' },
    ],
    events: [],
    avg_rating: 4.4,
    rating_count: 2,
  },
  {
    id: '19',
    name: 'Wolf Barcelona',
    type: 'discoteca',
    description: 'Accessible young club in Poblenou. Pop, electronic, K-pop and techno nights. 18+. Thu from €9, Fri €10–17, Sat €13–20.',
    address: 'Carrer dels Almogàvers, 88',
    neighborhood: 'Poblenou',
    lat: 41.4005,
    lng: 2.1945,
    ambients: ['pop', 'electronica', 'techno', 'kpop'],
    min_age: 18,
    dress_code: null,
    image_url: null,
    website: null,
    instagram: '@wolfbarcelona',
    phone: null,
    opening_hours: { 'Thu–Sat': 'from 23:00' },
    price_sync_url: null,
    price_sync_source: 'fourvenues',
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p19a', venue_id: '19', label: 'Entry – Thursday', amount: 9, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'dynamic', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: '2026-06-02T00:00:00Z',
        source: 'fourvenues', created_at: '2024-01-01',
      },
      {
        id: 'p19b', venue_id: '19', label: 'Entry – Friday', amount: 10, amount_max: 17,
        currency: 'EUR', includes: null, entrada_tipus: 'dynamic', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: '2026-06-02T00:00:00Z',
        source: 'fourvenues', created_at: '2024-01-01',
      },
      {
        id: 'p19c', venue_id: '19', label: 'Entry – Saturday', amount: 13, amount_max: 20,
        currency: 'EUR', includes: null, entrada_tipus: 'dynamic', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: '2026-06-02T00:00:00Z',
        source: 'fourvenues', created_at: '2024-01-01',
      },
    ],
    ratings: [
      { id: 'r19', venue_id: '19', user_id: null, score: 4, comment: 'Great K-pop nights, very inclusive crowd', ambients: ['kpop', 'pop'], created_at: '2024-01-01' },
      { id: 'r19b', venue_id: '19', user_id: null, score: 5, comment: 'Best electronic nights in Poblenou', ambients: ['electronica'], created_at: '2024-01-01' },
    ],
    events: [],
    avg_rating: 4.3,
    rating_count: 2,
  },
  {
    id: '20',
    name: 'Sala Apolo',
    type: 'discoteca',
    description: 'Legendary concert hall and club on Paral·lel. Electronic, pop and indie. Mon–Thu university nights (18–24), Fri–Sat electronic music lovers. Prices change nightly — auto-synced.',
    address: 'Carrer Nou de la Rambla, 113',
    neighborhood: 'Paral·lel',
    lat: 41.3745,
    lng: 2.1647,
    ambients: ['electronica', 'pop', 'indie', 'rock'],
    min_age: 18,
    dress_code: null,
    image_url: null,
    website: 'https://www.sala-apolo.com',
    instagram: '@salaapolo',
    phone: null,
    opening_hours: { 'Daily': '23:55–06:00' },
    price_sync_url: 'https://www.sala-apolo.com/agenda',
    price_sync_source: 'scraping',
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p20', venue_id: '20', label: 'Entry (varies by night)',
        amount: 10, amount_max: 14,
        currency: 'EUR', includes: null, entrada_tipus: 'dynamic', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: '2026-06-02T00:00:00Z',
        source: 'scraping', created_at: '2024-01-01',
      },
      {
        id: 'p20b', venue_id: '20', label: 'Cocktail / spirit', amount: 10, amount_max: 14,
        currency: 'EUR', includes: null, entrada_tipus: 'free', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
    ],
    ratings: [
      { id: 'r20', venue_id: '20', user_id: null, score: 4, comment: 'Iconic venue, great for electronic nights', ambients: ['electronica'], created_at: '2024-01-01' },
      { id: 'r20b', venue_id: '20', user_id: null, score: 5, comment: 'The best Monday student night in BCN', ambients: ['indie', 'pop'], created_at: '2024-01-01' },
    ],
    events: [],
    avg_rating: 4.3,
    rating_count: 2,
  },
  {
    id: '21',
    name: 'Twenties',
    type: 'discoteca',
    description: 'Elegant club in Zona Alta for young sophisticated crowd. Commercial and electronic music. Free entry with guest list.',
    address: 'Zona Alta, Sarrià-Sant Gervasi',
    neighborhood: 'Sarrià-Sant Gervasi',
    lat: 41.3975,
    lng: 2.1490,
    ambients: ['pijo', 'electronica', 'pop'],
    min_age: 18,
    dress_code: 'Smart elegant',
    image_url: null,
    website: null,
    instagram: '@twentiesbcn',
    phone: null,
    opening_hours: { 'Thu–Sat': 'from 23:30' },
    price_sync_url: null,
    price_sync_source: 'fourvenues',
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p21a', venue_id: '21', label: 'Free entry (guest list)', amount: 0, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free_list', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
      {
        id: 'p21b', venue_id: '21', label: 'Entry at door (variable)', amount: 10, amount_max: 20,
        currency: 'EUR', includes: null, entrada_tipus: 'dynamic', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: '2026-06-02T00:00:00Z',
        source: 'fourvenues', created_at: '2024-01-01',
      },
    ],
    ratings: [
      { id: 'r21', venue_id: '21', user_id: null, score: 4, comment: 'Classy, good music, nice interior', ambients: ['pijo'], created_at: '2024-01-01' },
    ],
    events: [],
    avg_rating: 4.0,
    rating_count: 1,
  },
  {
    id: '22',
    name: 'Costa Breve',
    type: 'discoteca',
    description: 'Selective upscale club on Tuset strip. House and commercial music. Free entry with VIP guest list only.',
    address: 'Carrer de Tuset, Zona Alta',
    neighborhood: 'Gràcia Alta',
    lat: 41.3972,
    lng: 2.1502,
    ambients: ['pijo', 'house', 'pop'],
    min_age: 18,
    dress_code: 'Smart — selective',
    image_url: null,
    website: null,
    instagram: null,
    phone: null,
    opening_hours: { 'Thu–Sat': 'from 23:30' },
    price_sync_url: null,
    price_sync_source: 'fourvenues',
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p22', venue_id: '22', label: 'Free entry (VIP guest list)', amount: 0, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free_list', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
    ],
    ratings: [
      { id: 'r22', venue_id: '22', user_id: null, score: 4, comment: 'Exclusive and sophisticated', ambients: ['pijo'], created_at: '2024-01-01' },
    ],
    events: [],
    avg_rating: 4.0,
    rating_count: 1,
  },
  {
    id: '23',
    name: 'Downtown',
    type: 'discoteca',
    description: 'Young mixed crowd in the city centre. Commercial hits. Free before 01:00 with guest list, paid entry after.',
    address: 'Barcelona centre',
    neighborhood: 'Eixample',
    lat: 41.3925,
    lng: 2.1620,
    ambients: ['pop', 'reggaeton', 'casual'],
    min_age: 18,
    dress_code: null,
    image_url: null,
    website: null,
    instagram: null,
    phone: null,
    opening_hours: { 'Thu–Sat': 'from 23:00' },
    price_sync_url: null,
    price_sync_source: 'fourvenues',
    created_at: '2024-01-01',
    prices: [
      {
        id: 'p23a', venue_id: '23', label: 'Free before 01:00 (guest list)', amount: 0, amount_max: null,
        currency: 'EUR', includes: null, entrada_tipus: 'free_list', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: null,
        source: 'manual', created_at: '2024-01-01',
      },
      {
        id: 'p23b', venue_id: '23', label: 'Entry after 01:00 (variable)', amount: 10, amount_max: 15,
        currency: 'EUR', includes: null, entrada_tipus: 'dynamic', is_current: true,
        valid_from: '2024-01-01', valid_to: null, last_synced_at: '2026-06-02T00:00:00Z',
        source: 'fourvenues', created_at: '2024-01-01',
      },
    ],
    ratings: [
      { id: 'r23', venue_id: '23', user_id: null, score: 4, comment: 'Good value, fun crowd', ambients: ['pop', 'casual'], created_at: '2024-01-01' },
    ],
    events: [],
    avg_rating: 3.9,
    rating_count: 1,
  },
]
